-- ONLINE BAR: ENGAGEMENT & WORLD BUILDING SCHEMA
-- Run this to enable Collections, Live City Pulse, and Advanced Crew Socials.

-- 1. COLLECTIONS (Discovery Goals)
CREATE TABLE IF NOT EXISTS public.collections (
    id TEXT PRIMARY KEY, -- e.g., 'NAIROBI_EXPLORER'
    name TEXT NOT NULL,
    description TEXT,
    icon TEXT,
    target_count INTEGER DEFAULT 10,
    category TEXT DEFAULT 'Exploration', -- Exploration, Beverage, Social
    xp_reward INTEGER DEFAULT 1000
);

CREATE TABLE IF NOT EXISTS public.user_collections (
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    collection_id TEXT REFERENCES public.collections(id) ON DELETE CASCADE,
    progress INTEGER DEFAULT 0,
    is_completed BOOLEAN DEFAULT false,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    PRIMARY KEY (user_id, collection_id)
);

-- 2. LIVE CITY PULSE (Marketplace Vibrancy)
CREATE TABLE IF NOT EXISTS public.neighborhood_trends (
    zone_name TEXT PRIMARY KEY, -- e.g., 'Westlands'
    active_visitors INTEGER DEFAULT 0,
    active_orders INTEGER DEFAULT 0,
    status TEXT DEFAULT 'Quiet', -- Trending, Busy, Elite Choice, Quiet
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 3. ADVANCED CREWS (Social Identity)
ALTER TABLE public.crews
ADD COLUMN IF NOT EXISTS logo_url TEXT,
ADD COLUMN IF NOT EXISTS motto TEXT,
ADD COLUMN IF NOT EXISTS rank_nairobi INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS season_xp INTEGER DEFAULT 0;

CREATE TABLE IF NOT EXISTS public.crew_challenges (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    description TEXT,
    target_xp INTEGER DEFAULT 10000,
    start_date TIMESTAMP WITH TIME ZONE,
    end_date TIMESTAMP WITH TIME ZONE,
    reward_multiplier NUMERIC DEFAULT 1.2
);

-- 4. PERSONALIZED QUESTS (AI Ready)
CREATE TABLE IF NOT EXISTS public.user_quests (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    xp_reward INTEGER DEFAULT 500,
    status TEXT DEFAULT 'Active', -- Active, Completed, Expired
    deadline TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 5. INITIAL COLLECTIONS DATA
INSERT INTO public.collections (id, name, description, icon, target_count, xp_reward)
VALUES
('NAIROBI_EXPLORER', 'Nairobi Explorer', 'Discover 10 different dispatch zones.', 'Map', 10, 1000),
('MIXOLOGY_MASTER', 'Mixology Master', 'Try 5 different spirits categories.', 'Wine', 5, 1500),
('SOCIAL_LEGEND', 'Social Legend', 'Join a crew and contribute 5000 XP.', 'Users', 500, 2000)
ON CONFLICT (id) DO NOTHING;

-- 6. INITIAL CITY TRENDS DATA
INSERT INTO public.neighborhood_trends (zone_name, status)
VALUES
('Westlands', 'Trending'),
('Kilimani', 'Busy'),
('CBD', 'Elite Choice'),
('Lavington', 'Quiet'),
('Karen', 'Busy')
ON CONFLICT (zone_name) DO NOTHING;

-- 7. SECURITY (RLS)
ALTER TABLE public.collections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_collections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.neighborhood_trends ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_quests ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Read Collections" ON public.collections FOR SELECT USING (true);
CREATE POLICY "Users view own collections" ON public.user_collections FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Public Read Trends" ON public.neighborhood_trends FOR SELECT USING (true);
CREATE POLICY "Users view own quests" ON public.user_quests FOR SELECT USING (auth.uid() = user_id);
