-- ONLINE BAR: MASTER GAMIFICATION ENGINE
-- Run this in the Supabase SQL Editor to enable XP, Levels, Achievements, and Seasons.

-- 1. PATRON PROGRESSION
ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS xp INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS level INTEGER DEFAULT 1,
ADD COLUMN IF NOT EXISTS title TEXT DEFAULT 'Newcomer';

-- 2. RUNNER & MERCHANT PROGRESSION
ALTER TABLE public.rider_status
ADD COLUMN IF NOT EXISTS runner_xp INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS runner_level INTEGER DEFAULT 1;

ALTER TABLE public.suppliers
ADD COLUMN IF NOT EXISTS merchant_xp INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS merchant_level INTEGER DEFAULT 1;

-- 3. ACHIEVEMENTS SYSTEM
CREATE TABLE IF NOT EXISTS public.achievements (
    key TEXT PRIMARY KEY,
    label TEXT NOT NULL,
    description TEXT,
    icon TEXT,
    xp_reward INTEGER DEFAULT 0,
    points_reward INTEGER DEFAULT 0,
    category TEXT DEFAULT 'Patron' -- Patron, Runner, Merchant
);

CREATE TABLE IF NOT EXISTS public.user_achievements (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    achievement_key TEXT REFERENCES public.achievements(key) ON DELETE CASCADE,
    unlocked_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    UNIQUE(user_id, achievement_key)
);

-- 4. SEASONS & EVENTS
CREATE TABLE IF NOT EXISTS public.seasons (
    id TEXT PRIMARY KEY, -- e.g. 'S01'
    name TEXT NOT NULL, -- e.g. 'Nairobi Nights'
    start_date TIMESTAMP WITH TIME ZONE NOT NULL,
    end_date TIMESTAMP WITH TIME ZONE NOT NULL,
    is_active BOOLEAN DEFAULT false
);

-- 5. CREWS (Teams)
CREATE TABLE IF NOT EXISTS public.crews (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT UNIQUE NOT NULL,
    founder_id UUID REFERENCES auth.users(id),
    total_xp INTEGER DEFAULT 0,
    member_count INTEGER DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.crew_members (
    crew_id BIGINT REFERENCES public.crews(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    joined_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    PRIMARY KEY (crew_id, user_id)
);

-- 6. TRIGGER: AUTOMATED LEVEL UP
CREATE OR REPLACE FUNCTION public.calculate_level(xp INTEGER)
RETURNS INTEGER AS $$
BEGIN
    -- Level formula: Level = floor(sqrt(xp / 100)) + 1
    RETURN floor(sqrt(xp / 100)) + 1;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

CREATE OR REPLACE FUNCTION public.trigger_level_up()
RETURNS TRIGGER AS $$
BEGIN
    NEW.level = public.calculate_level(NEW.xp);

    -- Update Title based on level
    IF NEW.level = 1 THEN NEW.title = 'Newcomer';
    ELSIF NEW.level = 2 THEN NEW.title = 'Regular';
    ELSIF NEW.level = 3 THEN NEW.title = 'Insider';
    ELSIF NEW.level = 4 THEN NEW.title = 'VIP';
    ELSIF NEW.level = 5 THEN NEW.title = 'Elite';
    ELSIF NEW.level >= 6 THEN NEW.title = 'Legend';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tr_patron_level_up ON public.profiles;
CREATE TRIGGER tr_patron_level_up
BEFORE UPDATE OF xp ON public.profiles
FOR EACH ROW EXECUTE PROCEDURE public.trigger_level_up();

-- 7. INITIAL ACHIEVEMENTS DATA
INSERT INTO public.achievements (key, label, description, icon, xp_reward, points_reward)
VALUES
('first-pour', 'First Pour', 'Completed your first bar order.', 'ShoppingBag', 100, 50),
('bar-regular', 'Bar Regular', 'Completed 5 orders in a month.', 'Wine', 500, 200),
('connoisseur', 'Connoisseur', 'Reviewed 5 different beverages.', 'MessageSquare', 300, 100),
('social-patron', 'Social Patron', 'Successfully referred a friend.', 'Users', 1000, 500)
ON CONFLICT (key) DO NOTHING;

-- 8. SECURITY (RLS)
ALTER TABLE public.achievements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_achievements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.seasons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crews ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Read Achievements" ON public.achievements FOR SELECT USING (true);
CREATE POLICY "Users view own achievements" ON public.user_achievements FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Public Read Seasons" ON public.seasons FOR SELECT USING (true);
CREATE POLICY "Public Read Crews" ON public.crews FOR SELECT USING (true);
