-- ONLINE BAR: FOUNDATION HARDENING & INTELLIGENCE
-- Run this AFTER master_setup.sql.

-- 1. PRODUCT INTELLIGENCE
ALTER TABLE public.products
ADD COLUMN IF NOT EXISTS abv NUMERIC,
ADD COLUMN IF NOT EXISTS origin TEXT,
ADD COLUMN IF NOT EXISTS taste_profile TEXT,
ADD COLUMN IF NOT EXISTS occasions TEXT[] DEFAULT ARRAY[]::TEXT[];

-- 2. RIDER SCHEMA EVOLUTION
ALTER TABLE public.rider_status
ADD COLUMN IF NOT EXISTS id_number TEXT,
ADD COLUMN IF NOT EXISTS license_number TEXT,
ADD COLUMN IF NOT EXISTS verification_docs JSONB DEFAULT '{}'::JSONB,
ADD COLUMN IF NOT EXISTS onboarding_step TEXT DEFAULT 'WELCOME',
ADD COLUMN IF NOT EXISTS last_known_lat NUMERIC,
ADD COLUMN IF NOT EXISTS last_known_lng NUMERIC,
ADD COLUMN IF NOT EXISTS current_otp TEXT;

-- 3. LOCATION HISTORY (High Frequency Tracking)
CREATE TABLE IF NOT EXISTS public.rider_location_history (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    rider_phone TEXT REFERENCES public.rider_status(rider_phone) ON DELETE CASCADE,
    latitude NUMERIC NOT NULL,
    longitude NUMERIC NOT NULL,
    accuracy NUMERIC,
    speed NUMERIC,
    heading NUMERIC,
    battery_level INTEGER,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Index for fast tracking lookups
CREATE INDEX IF NOT EXISTS idx_rider_location_timestamp ON public.rider_location_history(rider_phone, timestamp DESC);

-- 4. ONBOARDING RESUME STATE
CREATE TABLE IF NOT EXISTS public.rider_onboarding_sessions (
    rider_phone TEXT PRIMARY KEY REFERENCES public.rider_status(rider_phone) ON DELETE CASCADE,
    current_step TEXT DEFAULT 'WELCOME',
    form_data JSONB DEFAULT '{}'::JSONB,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 5. LOYALTY LEDGER
CREATE TABLE IF NOT EXISTS public.loyalty_ledger (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    amount INTEGER NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 6. SECURITY: IP TRACKING TRIGGER
CREATE OR REPLACE FUNCTION public.log_ip_address()
RETURNS TRIGGER AS $$
BEGIN
    NEW.details = jsonb_set(
        COALESCE(NEW.details, '{}'::JSONB),
        '{ip_address}',
        to_jsonb(inet_client_addr()::text)
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tr_log_ip ON public.audit_logs;
CREATE TRIGGER tr_log_ip
BEFORE INSERT ON public.audit_logs
FOR EACH ROW EXECUTE PROCEDURE public.log_ip_address();

-- 7. ENABLE ROW LEVEL SECURITY (RLS)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rider_status ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rider_location_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff ENABLE ROW LEVEL SECURITY;

-- 8. CORE POLICIES
DROP POLICY IF EXISTS "Public Read Products" ON public.products;
CREATE POLICY "Public Read Products" ON public.products FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users view own profile" ON public.profiles;
CREATE POLICY "Users view own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users see own orders" ON public.orders;
CREATE POLICY "Users see own orders" ON public.orders FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Public Insert Orders" ON public.orders;
CREATE POLICY "Public Insert Orders" ON public.orders FOR INSERT WITH CHECK (true);
