-- ONLINE BAR: MASTER SYSTEM SYNC
-- Run this first in the Supabase SQL Editor.

-- 1. PRODUCTS
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  price NUMERIC NOT NULL,
  old_price NUMERIC,
  cost_price NUMERIC DEFAULT 0,
  description TEXT,
  image_url TEXT,
  images TEXT[] DEFAULT ARRAY[]::TEXT[],
  video_url TEXT,
  category TEXT DEFAULT 'wine',
  sizes TEXT[] DEFAULT ARRAY['Standard'],
  stock INT DEFAULT 0,
  variant_stock JSONB DEFAULT '{}'::JSONB,
  tech_specs JSONB DEFAULT '{}'::JSONB,
  is_featured BOOLEAN DEFAULT false,
  featured_rank INT DEFAULT 99,
  is_new BOOLEAN DEFAULT true,
  sale_end_date TIMESTAMP WITH TIME ZONE,
  rating NUMERIC DEFAULT 5.0,
  status TEXT DEFAULT 'Live',
  supplier_id BIGINT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 2. PROFILES (Customers)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT,
  full_name TEXT,
  phone_number TEXT UNIQUE,
  address TEXT,
  latitude NUMERIC,
  longitude NUMERIC,
  birth_date DATE,
  referral_code TEXT UNIQUE,
  referral_clicks INTEGER DEFAULT 0,
  loyalty_points INTEGER DEFAULT 0,
  total_commission_earned NUMERIC DEFAULT 0,
  status_flag TEXT DEFAULT 'Active',
  current_streak INTEGER DEFAULT 0,
  last_streak_update TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 3. ORDERS
CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  session_id TEXT,
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  customer_email TEXT,
  product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
  quantity INT NOT NULL DEFAULT 1,
  size TEXT DEFAULT 'Standard',
  unit_price NUMERIC,
  unit_cost NUMERIC,
  total_price NUMERIC NOT NULL,
  status TEXT DEFAULT 'Pending',
  payment_method TEXT DEFAULT 'M-Pesa',
  checkout_request_id TEXT,
  payment_verified_at TIMESTAMP WITH TIME ZONE,
  note TEXT,
  referred_by_code TEXT,
  rider_name TEXT,
  rider_phone TEXT,
  captured_by TEXT DEFAULT 'system',
  latitude NUMERIC,
  longitude NUMERIC,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 4. RIDER STATUS
CREATE TABLE IF NOT EXISTS public.rider_status (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    rider_name TEXT NOT NULL,
    rider_phone TEXT UNIQUE NOT NULL,
    vehicle_type TEXT DEFAULT 'Motorbike',
    vehicle_reg TEXT,
    pin TEXT DEFAULT '1234',
    current_location TEXT,
    status TEXT DEFAULT 'Offline',
    battery_level INTEGER DEFAULT 100,
    total_deliveries INTEGER DEFAULT 0,
    rating DECIMAL DEFAULT 5.0,
    area_zone TEXT DEFAULT 'Nairobi',
    max_deliveries INTEGER DEFAULT 10,
    weekly_salary NUMERIC DEFAULT 0,
    health_score INTEGER DEFAULT 100,
    current_tier TEXT DEFAULT 'Bronze',
    acceptance_rate INTEGER DEFAULT 100,
    online_since TIMESTAMP WITH TIME ZONE,
    biometric_key JSONB,
    verification_status TEXT DEFAULT 'Pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 5. STAFF
CREATE TABLE IF NOT EXISTS public.staff (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT UNIQUE NOT NULL,
  role TEXT DEFAULT 'staff',
  pin TEXT,
  supplier_id BIGINT,
  can_view_revenue BOOLEAN DEFAULT false,
  can_manage_inventory BOOLEAN DEFAULT true,
  can_manage_orders BOOLEAN DEFAULT true,
  can_delete_items BOOLEAN DEFAULT false,
  can_manage_blog BOOLEAN DEFAULT false,
  can_manage_affiliates BOOLEAN DEFAULT false,
  can_manage_customer_care BOOLEAN DEFAULT false,
  can_manage_broadcast BOOLEAN DEFAULT false,
  can_manage_settings BOOLEAN DEFAULT false,
  can_manage_media BOOLEAN DEFAULT false,
  can_view_sensitive_rider_data BOOLEAN DEFAULT false,
  can_view_audit_logs BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 6. AUDIT LOGS
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    staff_email TEXT,
    action TEXT NOT NULL,
    details JSONB,
    ip_address TEXT,
    device_info TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 7. SETTINGS
CREATE TABLE IF NOT EXISTS public.settings (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL,
    is_published BOOLEAN DEFAULT true,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 8. MESSAGES
CREATE TABLE IF NOT EXISTS public.messages (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  subject TEXT DEFAULT 'In-App Support Ticket',
  message TEXT NOT NULL,
  status TEXT DEFAULT 'New',
  admin_response TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 9. AUTH TRIGGER (Automated Profile Creation)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, phone_number)
  VALUES (
    new.id,
    new.email,
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'phone_number'
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
