-- ==========================================
-- ONLINE BAR: RESILIENT MASTER BACKEND SETUP
-- This script ensures all tables, columns, and triggers exist.
-- Safe to run multiple times. Does NOT delete existing data.
-- ==========================================

-- 1. TABLE CREATION & COLUMN SYNCHRONIZATION
-- ------------------------------------------

-- PRODUCTS
CREATE TABLE IF NOT EXISTS public.products (id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY);
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS name TEXT DEFAULT 'Unnamed Bottle';
ALTER TABLE public.products ALTER COLUMN name SET NOT NULL;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS price NUMERIC DEFAULT 0;
ALTER TABLE public.products ALTER COLUMN price SET NOT NULL;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS old_price NUMERIC;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS cost_price NUMERIC DEFAULT 0;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS images TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS video_url TEXT;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'drinks';
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS sizes TEXT[] DEFAULT ARRAY['Standard'];
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS stock INT DEFAULT 0;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS variant_stock JSONB DEFAULT '{}'::JSONB;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS tech_specs JSONB DEFAULT '{}'::JSONB;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS is_featured BOOLEAN DEFAULT false;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS featured_rank INT DEFAULT 99;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS is_new BOOLEAN DEFAULT true;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS sale_end_date TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS rating NUMERIC DEFAULT 5.0;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'Live';
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS supplier_id BIGINT;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT now();
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT now();

-- PROFILES (Patrons)
CREATE TABLE IF NOT EXISTS public.profiles (id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE);
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS full_name TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS phone_number TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS latitude NUMERIC;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS longitude NUMERIC;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS birth_date DATE;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS referral_code TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS referral_clicks INTEGER DEFAULT 0;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS loyalty_points INTEGER DEFAULT 0;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS total_commission_earned NUMERIC DEFAULT 0;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS status_flag TEXT DEFAULT 'Active';
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS current_streak INTEGER DEFAULT 0;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS last_streak_update TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS xp INTEGER DEFAULT 0;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS level INTEGER DEFAULT 1;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS title TEXT DEFAULT 'Newcomer';
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS segment TEXT DEFAULT 'New';
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS lifetime_value NUMERIC DEFAULT 0;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS total_orders INTEGER DEFAULT 0;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS last_purchase_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT now();

-- SUPPLIERS
CREATE TABLE IF NOT EXISTS public.suppliers (id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY);
ALTER TABLE public.suppliers ADD COLUMN IF NOT EXISTS name TEXT DEFAULT 'Unnamed Supplier';
ALTER TABLE public.suppliers ALTER COLUMN name SET NOT NULL;
ALTER TABLE public.suppliers ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE public.suppliers ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE public.suppliers ADD COLUMN IF NOT EXISTS bank_details JSONB DEFAULT '{}'::JSONB;
ALTER TABLE public.suppliers ADD COLUMN IF NOT EXISTS categories TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE public.suppliers ADD COLUMN IF NOT EXISTS rating NUMERIC DEFAULT 100.0;
ALTER TABLE public.suppliers ADD COLUMN IF NOT EXISTS fill_rate NUMERIC DEFAULT 0.0;
ALTER TABLE public.suppliers ADD COLUMN IF NOT EXISTS on_time_dispatch_rate NUMERIC DEFAULT 0.0;
ALTER TABLE public.suppliers ADD COLUMN IF NOT EXISTS defect_rate NUMERIC DEFAULT 0.0;
ALTER TABLE public.suppliers ADD COLUMN IF NOT EXISTS merchant_xp INTEGER DEFAULT 0;
ALTER TABLE public.suppliers ADD COLUMN IF NOT EXISTS merchant_level INTEGER DEFAULT 1;
ALTER TABLE public.suppliers ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;
ALTER TABLE public.suppliers ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT now();
ALTER TABLE public.suppliers ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT now();

-- ORDERS
CREATE TABLE IF NOT EXISTS public.orders (id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY);
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS session_id TEXT;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS customer_name TEXT DEFAULT 'Guest';
ALTER TABLE public.orders ALTER COLUMN customer_name SET NOT NULL;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS customer_phone TEXT;
ALTER TABLE public.orders ALTER COLUMN customer_phone SET NOT NULL;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS customer_email TEXT;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS quantity INT DEFAULT 1;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS size TEXT DEFAULT 'Standard';
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS unit_price NUMERIC DEFAULT 0;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS unit_cost NUMERIC DEFAULT 0;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS total_price NUMERIC DEFAULT 0;
ALTER TABLE public.orders ALTER COLUMN total_price SET NOT NULL;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS total_cost NUMERIC DEFAULT 0;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS fees_paid NUMERIC DEFAULT 0;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS delivery_cost NUMERIC DEFAULT 0;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS risk_score INTEGER DEFAULT 0;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'Pending';
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS payment_method TEXT DEFAULT 'M-Pesa';
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS checkout_request_id TEXT;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS payment_verified_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS note TEXT;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS referred_by_code TEXT;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS rider_name TEXT;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS rider_phone TEXT;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS captured_by TEXT DEFAULT 'system';
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS latitude NUMERIC;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS longitude NUMERIC;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS transition_reason TEXT;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT now();
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT now();

-- INVENTORY UNITS
CREATE TABLE IF NOT EXISTS public.inventory_units (id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY);
ALTER TABLE public.inventory_units ADD COLUMN IF NOT EXISTS product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE;
ALTER TABLE public.inventory_units ADD COLUMN IF NOT EXISTS supplier_id BIGINT REFERENCES public.suppliers(id) ON DELETE SET NULL;
ALTER TABLE public.inventory_units ADD COLUMN IF NOT EXISTS serial_number TEXT;
ALTER TABLE public.inventory_units ADD COLUMN IF NOT EXISTS imei TEXT;
ALTER TABLE public.inventory_units ADD COLUMN IF NOT EXISTS cost_price NUMERIC DEFAULT 0;
ALTER TABLE public.inventory_units ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'Available';
ALTER TABLE public.inventory_units ADD COLUMN IF NOT EXISTS order_id BIGINT REFERENCES public.orders(id) ON DELETE SET NULL;
ALTER TABLE public.inventory_units ADD COLUMN IF NOT EXISTS received_at TIMESTAMP WITH TIME ZONE DEFAULT now();
ALTER TABLE public.inventory_units ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT now();

-- RIDER STATUS
CREATE TABLE IF NOT EXISTS public.rider_status (id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY);
ALTER TABLE public.rider_status ADD COLUMN IF NOT EXISTS rider_name TEXT DEFAULT 'Unknown Runner';
ALTER TABLE public.rider_status ALTER COLUMN rider_name SET NOT NULL;
ALTER TABLE public.rider_status ADD COLUMN IF NOT EXISTS rider_phone TEXT;
ALTER TABLE public.rider_status ALTER COLUMN rider_phone SET NOT NULL;
ALTER TABLE public.rider_status ADD COLUMN IF NOT EXISTS vehicle_type TEXT DEFAULT 'Motorbike';
ALTER TABLE public.rider_status ADD COLUMN IF NOT EXISTS vehicle_reg TEXT;
ALTER TABLE public.rider_status ADD COLUMN IF NOT EXISTS id_number TEXT;
ALTER TABLE public.rider_status ADD COLUMN IF NOT EXISTS license_number TEXT;
ALTER TABLE public.rider_status ADD COLUMN IF NOT EXISTS verification_status TEXT DEFAULT 'Pending';
ALTER TABLE public.rider_status ADD COLUMN IF NOT EXISTS verification_docs JSONB DEFAULT '{}'::JSONB;
ALTER TABLE public.rider_status ADD COLUMN IF NOT EXISTS pin TEXT DEFAULT '1234';
ALTER TABLE public.rider_status ADD COLUMN IF NOT EXISTS current_otp TEXT;
ALTER TABLE public.rider_status ADD COLUMN IF NOT EXISTS current_location TEXT;
ALTER TABLE public.rider_status ADD COLUMN IF NOT EXISTS last_known_lat NUMERIC;
ALTER TABLE public.rider_status ADD COLUMN IF NOT EXISTS last_known_lng NUMERIC;
ALTER TABLE public.rider_status ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'Offline';
ALTER TABLE public.rider_status ADD COLUMN IF NOT EXISTS battery_level INTEGER DEFAULT 100;
ALTER TABLE public.rider_status ADD COLUMN IF NOT EXISTS total_deliveries INTEGER DEFAULT 0;
ALTER TABLE public.rider_status ADD COLUMN IF NOT EXISTS rating DECIMAL DEFAULT 5.0;
ALTER TABLE public.rider_status ADD COLUMN IF NOT EXISTS area_zone TEXT DEFAULT 'Nairobi';
ALTER TABLE public.rider_status ADD COLUMN IF NOT EXISTS max_deliveries INTEGER DEFAULT 10;
ALTER TABLE public.rider_status ADD COLUMN IF NOT EXISTS weekly_salary NUMERIC DEFAULT 0;
ALTER TABLE public.rider_status ADD COLUMN IF NOT EXISTS health_score INTEGER DEFAULT 100;
ALTER TABLE public.rider_status ADD COLUMN IF NOT EXISTS current_tier TEXT DEFAULT 'Bronze';
ALTER TABLE public.rider_status ADD COLUMN IF NOT EXISTS acceptance_rate INTEGER DEFAULT 100;
ALTER TABLE public.rider_status ADD COLUMN IF NOT EXISTS runner_xp INTEGER DEFAULT 0;
ALTER TABLE public.rider_status ADD COLUMN IF NOT EXISTS runner_level INTEGER DEFAULT 1;
ALTER TABLE public.rider_status ADD COLUMN IF NOT EXISTS online_since TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.rider_status ADD COLUMN IF NOT EXISTS biometric_key JSONB;
ALTER TABLE public.rider_status ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT now();
ALTER TABLE public.rider_status ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT now();

-- 2. GAMIFICATION TABLES
-- ------------------------------------------

CREATE TABLE IF NOT EXISTS public.achievements (
    key TEXT PRIMARY KEY,
    label TEXT NOT NULL,
    description TEXT,
    icon TEXT,
    xp_reward INTEGER DEFAULT 0,
    points_reward INTEGER DEFAULT 0,
    category TEXT DEFAULT 'Patron'
);

CREATE TABLE IF NOT EXISTS public.user_achievements (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    achievement_key TEXT REFERENCES public.achievements(key) ON DELETE CASCADE,
    unlocked_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    UNIQUE(user_id, achievement_key)
);

CREATE TABLE IF NOT EXISTS public.seasons (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    start_date TIMESTAMP WITH TIME ZONE NOT NULL,
    end_date TIMESTAMP WITH TIME ZONE NOT NULL,
    is_active BOOLEAN DEFAULT false
);

CREATE TABLE IF NOT EXISTS public.crews (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT UNIQUE NOT NULL,
    founder_id UUID REFERENCES auth.users(id),
    total_xp INTEGER DEFAULT 0,
    member_count INTEGER DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.crew_members (
    crew_id BIGINT REFERENCES public.crews(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    joined_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    PRIMARY KEY (crew_id, user_id)
);

-- 3. INTELLIGENCE & INFRASTRUCTURE
-- ------------------------------------------

CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    staff_email TEXT,
    action TEXT NOT NULL,
    details JSONB,
    ip_address TEXT,
    device_info TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.settings (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL,
    is_published BOOLEAN DEFAULT true,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.active_visitors (
  session_id TEXT PRIMARY KEY,
  customer_name TEXT,
  current_page TEXT,
  latitude NUMERIC,
  longitude NUMERIC,
  last_active_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  cart_value NUMERIC DEFAULT 0,
  status TEXT DEFAULT 'Browsing'
);

-- 4. FUNCTIONS & TRIGGERS (Auto Level Up)
-- ------------------------------------------

CREATE OR REPLACE FUNCTION public.calculate_level(xp INTEGER)
RETURNS INTEGER AS $$
BEGIN
    RETURN floor(sqrt(xp / 100)) + 1;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

CREATE OR REPLACE FUNCTION public.trigger_level_up()
RETURNS TRIGGER AS $$
BEGIN
    NEW.level = public.calculate_level(NEW.xp);
    IF NEW.level = 1 THEN NEW.title = 'Newcomer';
    ELSIF NEW.level = 2 THEN NEW.title = 'Regular';
    ELSIF NEW.level = 3 THEN NEW.title = 'Insider';
    ELSIF NEW.level = 4 THEN NEW.title = 'VIP';
    ELSIF NEW.level = 5 THEN NEW.title = 'Elite';
    ELSIF NEW.level >= 6 THEN NEW.title = 'Legend';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tr_patron_level_up ON public.profiles;
CREATE TRIGGER tr_patron_level_up
BEFORE UPDATE OF xp ON public.profiles
FOR EACH ROW EXECUTE PROCEDURE public.trigger_level_up();

-- 5. INITIAL DATA SEED
-- ------------------------------------------

INSERT INTO public.achievements (key, label, description, icon, xp_reward, points_reward)
VALUES
('first-pour', 'First Pour', 'Completed your first bar order.', 'ShoppingBag', 100, 50),
('bar-regular', 'Bar Regular', 'Completed 5 orders in a month.', 'Wine', 500, 200),
('connoisseur', 'Connoisseur', 'Reviewed 5 different beverages.', 'MessageSquare', 300, 100),
('social-patron', 'Social Patron', 'Successfully referred a friend.', 'Users', 1000, 500)
ON CONFLICT (key) DO NOTHING;

INSERT INTO public.seasons (id, name, start_date, end_date, is_active)
VALUES ('S01', 'Nairobi Nights', now(), now() + interval '30 days', true)
ON CONFLICT (id) DO NOTHING;

-- 6. RLS POLICIES (Enforce Security)
-- ------------------------------------------

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rider_status ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.achievements ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Read Products" ON public.products;
CREATE POLICY "Public Read Products" ON public.products FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users view own profile" ON public.profiles;
CREATE POLICY "Users view own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);

DROP POLICY IF EXISTS "Admins see all riders" ON public.rider_status;
CREATE POLICY "Admins see all riders" ON public.rider_status FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Public Read Achievements" ON public.achievements;
CREATE POLICY "Public Read Achievements" ON public.achievements FOR SELECT USING (true);
