-- ==========================================
-- ONLINE BAR OS: MASTER ESTABLISHMENT V4
-- ==========================================
-- ⚠️ Instructions: Run this entire script in your Supabase SQL Editor once.

-- 1. REPAIR & HARDEN ORDERS TABLE
ALTER TABLE IF EXISTS public.orders
ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid(),
ADD COLUMN IF NOT EXISTS session_id TEXT,
ADD COLUMN IF NOT EXISTS unit_price NUMERIC,
ADD COLUMN IF NOT EXISTS unit_cost NUMERIC,
ADD COLUMN IF NOT EXISTS size TEXT DEFAULT 'Standard',
ADD COLUMN IF NOT EXISTS checkout_request_id TEXT,
ADD COLUMN IF NOT EXISTS captured_by TEXT DEFAULT 'system',
ADD COLUMN IF NOT EXISTS latitude NUMERIC,
ADD COLUMN IF NOT EXISTS longitude NUMERIC,
ADD COLUMN IF NOT EXISTS customer_email TEXT;

CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_session_id ON orders(session_id);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at DESC);

-- 2. PRODUCTS & INVENTORY SCHEMA
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  brand TEXT,
  sku TEXT UNIQUE,
  price NUMERIC NOT NULL,
  old_price NUMERIC,
  cost_price NUMERIC DEFAULT 0,
  description TEXT,
  image_url TEXT,
  images TEXT[] DEFAULT ARRAY[]::TEXT[],
  video_url TEXT,
  category TEXT DEFAULT 'spirits',
  sizes TEXT[] DEFAULT ARRAY['Standard'],
  stock INT DEFAULT 0,
  variant_stock JSONB DEFAULT '{}'::JSONB,
  tech_specs JSONB DEFAULT '{}'::JSONB,
  beverage_specs JSONB DEFAULT '{}'::JSONB,
  is_featured BOOLEAN DEFAULT false,
  featured_rank INT DEFAULT 99,
  is_new BOOLEAN DEFAULT true,
  is_snack BOOLEAN DEFAULT false,
  sub_category TEXT,
  status TEXT DEFAULT 'Live',
  sale_end_date TIMESTAMP WITH TIME ZONE,
  rating NUMERIC DEFAULT 5.0,
  warehouse_location TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 3. IDENTITY & TASTE DNA
ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS taste_dna JSONB DEFAULT '{"whiskey": 0, "wine": 0, "gin": 0, "beer": 0, "vodka": 0, "tequila": 0}'::JSONB;

-- 4. BEHAVIORAL ANALYTICS & VISITOR HUD
CREATE TABLE IF NOT EXISTS public.active_visitors (
  session_id TEXT PRIMARY KEY,
  customer_name TEXT,
  current_page TEXT,
  last_active_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  cart_value NUMERIC DEFAULT 0,
  latitude NUMERIC,
  longitude NUMERIC,
  status TEXT DEFAULT 'Browsing'
);

CREATE TABLE IF NOT EXISTS public.analytics_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_name TEXT NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    anonymous_id TEXT,
    session_id TEXT,
    payload JSONB DEFAULT '{}'::JSONB,
    source TEXT DEFAULT 'WEB',
    page_url TEXT,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 5. REVIEWS & COMMUNICATIONS
CREATE TABLE IF NOT EXISTS public.reviews (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
  customer_name TEXT NOT NULL,
  rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.messages (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  subject TEXT DEFAULT 'In-App Support Ticket',
  message TEXT NOT NULL,
  status TEXT DEFAULT 'New',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 6. SECURITY & LOGINS
CREATE TABLE IF NOT EXISTS public.login_attempts (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  success BOOLEAN NOT NULL,
  ip_address TEXT DEFAULT 'unknown',
  attempt_time TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 7. RIDER ECONOMY & INTELLIGENCE
CREATE TABLE IF NOT EXISTS public.rider_status (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    rider_phone TEXT UNIQUE NOT NULL,
    rider_name TEXT NOT NULL,
    status TEXT DEFAULT 'Offline',
    battery_level INTEGER DEFAULT 100,
    latitude NUMERIC,
    longitude NUMERIC,
    last_ping TIMESTAMP WITH TIME ZONE DEFAULT now(),
    online_since TIMESTAMP WITH TIME ZONE,
    current_tier TEXT DEFAULT 'Bronze',
    acceptance_rate NUMERIC DEFAULT 100
);

CREATE TABLE IF NOT EXISTS public.rider_wallets (
  rider_phone TEXT PRIMARY KEY REFERENCES rider_status(rider_phone),
  balance NUMERIC DEFAULT 0,
  total_earned NUMERIC DEFAULT 0,
  payout_method TEXT DEFAULT 'M-Pesa',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 8. STORAGE BUCKET POLICIES (Run in SQL editor if not using UI)
-- Ensure 'apexstores-assets' bucket is created in Storage first.
INSERT INTO storage.buckets (id, name, public)
VALUES ('apexstores-assets', 'apexstores-assets', true)
ON CONFLICT (id) DO NOTHING;

-- Policies for apexstores-assets
CREATE POLICY "Public read" ON storage.objects FOR SELECT USING (bucket_id = 'apexstores-assets');
CREATE POLICY "Authenticated insert" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'apexstores-assets');
CREATE POLICY "Authenticated delete" ON storage.objects FOR DELETE USING (bucket_id = 'apexstores-assets');

-- 9. PERFORMANCE TUNING INDICES
CREATE INDEX IF NOT EXISTS idx_analytics_name_time ON public.analytics_events(event_name, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_analytics_timestamp ON public.analytics_events(timestamp DESC);

NOTIFY pgrst, 'reload schema';
