-- ==========================================
-- ONLINE BAR: MASTER ESTABLISHMENT SCRIPT
-- ==========================================
-- Consolidates all tables, relationships, and triggers for a 100% functional grid.
-- Run this in your Supabase SQL Editor.

-- 1. CORE IDENTITY & PROFILES (Capturing Phone & Address)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT,
  full_name TEXT,
  phone_number TEXT UNIQUE,
  address TEXT,
  latitude NUMERIC,
  longitude NUMERIC,
  referral_code TEXT UNIQUE,
  loyalty_points INTEGER DEFAULT 0,
  xp INTEGER DEFAULT 0,
  level INTEGER DEFAULT 1,
  title TEXT DEFAULT 'Newcomer',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 2. PRODUCTS & CELLAR (Hardened with Quality Scoring)
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  brand TEXT,
  sku TEXT UNIQUE,
  price NUMERIC NOT NULL,
  cost_price NUMERIC DEFAULT 0,
  description TEXT,
  image_url TEXT,
  images TEXT[] DEFAULT ARRAY[]::TEXT[],
  category TEXT DEFAULT 'wine',
  stock INT DEFAULT 0,
  warehouse_location TEXT,
  beverage_specs JSONB DEFAULT '{}'::JSONB,
  image_quality_score INTEGER DEFAULT 0,
  image_metadata JSONB DEFAULT '{}'::JSONB,
  status TEXT DEFAULT 'Live',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 3. ORDERS & DISPATCH
CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  total_price NUMERIC NOT NULL,
  status TEXT DEFAULT 'Created',
  payment_method TEXT DEFAULT 'M-Pesa',
  rider_name TEXT,
  rider_phone TEXT,
  warehouse_location TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.order_items (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    quantity INT NOT NULL DEFAULT 1,
    unit_price NUMERIC NOT NULL,
    unit_cost NUMERIC NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 4. STAFF ACCOUNTABILITY
CREATE TABLE IF NOT EXISTS public.staff (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT UNIQUE NOT NULL,
  role TEXT DEFAULT 'STAFF',
  pin TEXT,
  status TEXT DEFAULT 'Offline',
  last_activity_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  completed_tasks INTEGER DEFAULT 0,
  overdue_tasks INTEGER DEFAULT 0,
  sla_rating NUMERIC DEFAULT 100.0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 5. FINANCE & MASTER LEDGER
CREATE TABLE IF NOT EXISTS public.financial_ledger (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE SET NULL,
    entry_type TEXT NOT NULL, -- 'REVENUE', 'SUPPLIER_PAYABLE', 'COST', 'PAYMENT_FEE'
    amount NUMERIC NOT NULL,
    description TEXT,
    is_reconciled BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 6. RIDER ECOSYSTEM
CREATE TABLE IF NOT EXISTS public.rider_status (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    rider_name TEXT NOT NULL,
    rider_phone TEXT UNIQUE NOT NULL,
    status TEXT DEFAULT 'Offline',
    battery_level INTEGER DEFAULT 100,
    rating DECIMAL DEFAULT 5.0,
    area_zone TEXT DEFAULT 'Nairobi',
    current_tier TEXT DEFAULT 'Bronze',
    onboarding_step TEXT DEFAULT 'WELCOME',
    verification_status TEXT DEFAULT 'Pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.rider_location_history (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    rider_phone TEXT REFERENCES public.rider_status(rider_phone) ON DELETE CASCADE,
    latitude NUMERIC NOT NULL,
    longitude NUMERIC NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 7. AUDIT LOGS (Security Node)
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    staff_email TEXT,
    action TEXT NOT NULL,
    details JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 8. SECURITY NODES
CREATE TABLE IF NOT EXISTS public.login_attempts (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  success BOOLEAN NOT NULL,
  ip_address TEXT DEFAULT 'unknown',
  attempt_time TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.security_threats (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    type TEXT NOT NULL,
    severity TEXT,
    status TEXT DEFAULT 'Flagged',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 9. TRIGGERS & AUTOMATION

-- A. Auth to Profile Sync (Auto-capture Address/Phone on Signup)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, phone_number, address)
  VALUES (
    new.id,
    new.email,
    NULLIF(new.raw_user_meta_data->>'full_name', ''),
    NULLIF(new.raw_user_meta_data->>'phone_number', ''),
    NULLIF(new.raw_user_meta_data->>'address', '')
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- B. Staff Heartbeat (Real-time Status tracking)
CREATE OR REPLACE FUNCTION public.track_staff_heartbeat()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE public.staff
    SET
        last_activity_at = NOW(),
        status = 'Online'
    WHERE email = NEW.staff_email;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tr_staff_heartbeat ON public.audit_logs;
CREATE TRIGGER tr_staff_heartbeat
AFTER INSERT ON public.audit_logs
FOR EACH ROW EXECUTE PROCEDURE public.track_staff_heartbeat();

-- ==========================================
-- END OF MASTER SCRIPT
-- ==========================================
