-- ==================================================
-- ONLINE BAR: MASTER SYNC SCRIPT (HARDENED v2.0)
-- ==================================================
-- unifies all core tables, intelligence engines, and financial protocols.
-- Run this in your Supabase SQL Editor.

-- 1. EXTENDED PROFILES (CRM & Acquisition)
ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS lifetime_value NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_orders INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS last_purchase_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS segment TEXT DEFAULT 'Newcomer', -- VIP Premium, High Value, Repeat Buyer
ADD COLUMN IF NOT EXISTS preferred_comm_channel TEXT DEFAULT 'WhatsApp',
ADD COLUMN IF NOT EXISTS marketing_consent BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS first_touch_source TEXT,
ADD COLUMN IF NOT EXISTS first_touch_campaign TEXT,
ADD COLUMN IF NOT EXISTS conversion_date TIMESTAMP WITH TIME ZONE;

-- 2. CUSTOMER INTELLIGENCE SCHEMA
CREATE TABLE IF NOT EXISTS public.customer_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id),
    anonymous_id TEXT,
    source_channel TEXT,
    entry_page TEXT,
    exit_page TEXT,
    total_dwell_time_sec INTEGER DEFAULT 0,
    is_converted BOOLEAN DEFAULT false,
    device_info JSONB DEFAULT '{}'::JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.session_forensics (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    session_id UUID REFERENCES public.customer_sessions(id) ON DELETE CASCADE,
    action_type TEXT NOT NULL,
    page_url TEXT,
    metadata JSONB DEFAULT '{}'::JSONB,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.customer_intelligence (
    user_id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
    intent_score INTEGER DEFAULT 0,
    churn_risk_score INTEGER DEFAULT 0,
    purchase_intent_rank TEXT DEFAULT 'LOW',
    predicted_next_action TEXT,
    last_interaction_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.customer_product_preferences (
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    category_id TEXT,
    affinity_score INTEGER DEFAULT 0,
    purchase_count INTEGER DEFAULT 0,
    view_count INTEGER DEFAULT 0,
    last_interaction_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    PRIMARY KEY (user_id, category_id)
);

-- 3. FINANCE OS CORE
CREATE TABLE IF NOT EXISTS public.financial_ledger (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE SET NULL,
    entry_type TEXT NOT NULL, -- 'REVENUE', 'SUPPLIER_PAYABLE', 'COST', 'PAYMENT_FEE'
    amount NUMERIC NOT NULL,
    description TEXT,
    is_reconciled BOOLEAN DEFAULT false,
    reconciliation_ref TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.tax_configurations (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tax_name TEXT NOT NULL,
    rate_percent NUMERIC NOT NULL,
    tariff_code TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.reconciliation_staging (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    transaction_ref TEXT UNIQUE NOT NULL,
    source TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    transacted_at TIMESTAMP WITH TIME ZONE NOT NULL,
    is_matched BOOLEAN DEFAULT false,
    matched_order_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 4. SYSTEM AUTONOMOUS STATE
CREATE TABLE IF NOT EXISTS public.system_autonomous_state (
    engine_name TEXT PRIMARY KEY,
    is_autonomous BOOLEAN DEFAULT true,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 5. TRIGGER: CRM Sync (LTV & Segmentation)
CREATE OR REPLACE FUNCTION public.sync_customer_crm_stats()
RETURNS trigger AS $$
DECLARE
    cust_id UUID;
    v_total_spend NUMERIC;
    v_order_count INTEGER;
    v_segment TEXT;
BEGIN
    SELECT user_id INTO cust_id FROM public.orders WHERE id = NEW.id;

    IF cust_id IS NOT NULL AND NEW.status = 'Delivered' AND OLD.status != 'Delivered' THEN
        SELECT SUM(total_price), COUNT(id)
        INTO v_total_spend, v_order_count
        FROM public.orders
        WHERE user_id = cust_id AND status = 'Delivered';

        IF v_total_spend >= 100000 OR v_order_count >= 10 THEN v_segment := 'VIP Premium';
        ELSIF v_total_spend >= 50000 THEN v_segment := 'High Value';
        ELSE v_segment := 'Repeat Buyer';
        END IF;

        UPDATE public.profiles
        SET lifetime_value = v_total_spend,
            total_orders = v_order_count,
            segment = v_segment,
            last_purchase_at = NOW(),
            conversion_date = COALESCE(conversion_date, NOW())
        WHERE id = cust_id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tr_sync_customer_crm ON public.orders;
CREATE TRIGGER tr_sync_customer_crm
    AFTER UPDATE ON public.orders
    FOR EACH ROW EXECUTE PROCEDURE public.sync_customer_crm_stats();

-- 6. RPC: Real-time Dwell Tracking
CREATE OR REPLACE FUNCTION public.increment_session_dwell_time(sess_id UUID, inc_sec INTEGER)
RETURNS VOID AS $$
BEGIN
    UPDATE public.customer_sessions
    SET total_dwell_time_sec = total_dwell_time_sec + inc_sec,
        updated_at = NOW()
    WHERE id = sess_id;
END;
$$ LANGUAGE plpgsql;

-- 7. INITIAL DATA
INSERT INTO public.system_autonomous_state (engine_name)
VALUES ('Inventory'), ('Pricing'), ('Logistics'), ('Security')
ON CONFLICT DO NOTHING;

INSERT INTO public.tax_configurations (tax_name, rate_percent)
VALUES ('VAT', 16.0)
ON CONFLICT DO NOTHING;
