-- ==================================================
-- ONLINE BAR: MASTER ESTABLISHMENT SCRIPT (HARDENED v3.0)
-- ==================================================
-- Consolidates all 30+ tables, triggers, and security policies.
-- Run this in your Supabase SQL Editor to establish the full grid.

-- 0. CLEANUP (Optional - Use with caution if resetting)
-- DROP SCHEMA public CASCADE;
-- CREATE SCHEMA public;

-- 1. CORE IDENTITY & PROFILES
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT,
  full_name TEXT,
  phone_number TEXT UNIQUE,
  address TEXT,
  birth_date DATE,
  referral_code TEXT UNIQUE,
  loyalty_points INTEGER DEFAULT 0,
  xp INTEGER DEFAULT 0,
  level INTEGER DEFAULT 1,
  title TEXT DEFAULT 'Newcomer',
  lifetime_value NUMERIC DEFAULT 0,
  total_orders INTEGER DEFAULT 0,
  last_purchase_at TIMESTAMP WITH TIME ZONE,
  status_flag TEXT DEFAULT 'Active',
  segment TEXT DEFAULT 'New Customer',
  membership_tier TEXT DEFAULT 'Standard', -- 'Standard', 'Black'
  taste_dna JSONB DEFAULT '{"whiskey": 0, "wine": 0, "gin": 0, "beer": 0, "vodka": 0, "tequila": 0}'::JSONB,
  marketing_consent BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 2. PRODUCTS & CELLAR
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  brand TEXT,
  sku TEXT UNIQUE,
  price NUMERIC NOT NULL,
  old_price NUMERIC,
  cost_price NUMERIC DEFAULT 0,
  description TEXT,
  image_url TEXT,
  images TEXT[] DEFAULT ARRAY[]::TEXT[],
  category TEXT DEFAULT 'wine',
  stock INT DEFAULT 0,
  warehouse_location TEXT,
  beverage_specs JSONB DEFAULT '{}'::JSONB,
  image_quality_score INTEGER DEFAULT 0,
  status TEXT DEFAULT 'Live',
  is_featured BOOLEAN DEFAULT false,
  is_snack BOOLEAN DEFAULT false,
  is_new BOOLEAN DEFAULT true,
  rating NUMERIC DEFAULT 5.0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 3. ORDERS & DISPATCH
CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  session_id TEXT,
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  customer_email TEXT,
  total_price NUMERIC NOT NULL,
  status TEXT DEFAULT 'Created',
  payment_method TEXT DEFAULT 'M-Pesa',
  checkout_request_id TEXT,
  product_id BIGINT, -- Legacy support
  quantity INTEGER DEFAULT 1, -- Legacy support
  rider_name TEXT,
  rider_phone TEXT,
  note TEXT,
  referred_by_code TEXT,
  attribution_id TEXT,
  captured_by TEXT DEFAULT 'system',
  warehouse_location TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.order_items (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    quantity INT NOT NULL DEFAULT 1,
    unit_price NUMERIC NOT NULL,
    unit_cost NUMERIC NOT NULL,
    size TEXT DEFAULT 'Standard',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 4. FINANCE OS (Double-Entry Ledger)
CREATE TABLE IF NOT EXISTS public.ledger_accounts (
    id TEXT PRIMARY KEY, -- e.g., '1000', '4000'
    name TEXT NOT NULL,
    type TEXT NOT NULL, -- 'ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'COGS', 'EXPENSE'
    balance NUMERIC DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.ledger_transactions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    reference_type TEXT NOT NULL, -- 'ORDER', 'WITHDRAWAL', 'REFUND'
    reference_id TEXT NOT NULL,
    description TEXT,
    metadata JSONB DEFAULT '{}'::JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.ledger_entries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    transaction_id UUID REFERENCES public.ledger_transactions(id) ON DELETE CASCADE,
    account_id TEXT REFERENCES public.ledger_accounts(id) ON DELETE CASCADE,
    amount NUMERIC NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Legacy Compatibility View (If needed)
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'financial_ledger' AND table_type = 'BASE TABLE') THEN
        DROP TABLE public.financial_ledger CASCADE;
    END IF;
END $$;

CREATE OR REPLACE VIEW public.financial_ledger AS
SELECT
    le.id::text as legacy_id,
    le.id,
    lt.reference_id as order_id,
    la.type as entry_type,
    le.amount,
    lt.description,
    le.created_at
FROM public.ledger_entries le
JOIN public.ledger_transactions lt ON le.transaction_id = lt.id
JOIN public.ledger_accounts la ON le.account_id = la.id;

-- 5. RIDER ECOSYSTEM
CREATE TABLE IF NOT EXISTS public.rider_status (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    rider_name TEXT NOT NULL,
    rider_phone TEXT UNIQUE NOT NULL,
    status TEXT DEFAULT 'Offline',
    battery_level INTEGER DEFAULT 100,
    rating DECIMAL DEFAULT 5.0,
    area_zone TEXT DEFAULT 'Nairobi',
    current_tier TEXT DEFAULT 'Bronze',
    onboarding_step TEXT DEFAULT 'WELCOME',
    verification_status TEXT DEFAULT 'Pending',
    pin TEXT DEFAULT '1234',
    health_score INTEGER DEFAULT 100,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.rider_wallets (
    rider_phone TEXT PRIMARY KEY REFERENCES public.rider_status(rider_phone) ON DELETE CASCADE,
    balance NUMERIC DEFAULT 0,
    total_earned NUMERIC DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 6. STAFF & AUDIT
CREATE TABLE IF NOT EXISTS public.staff (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT UNIQUE NOT NULL,
  role TEXT DEFAULT 'STAFF',
  pin TEXT,
  status TEXT DEFAULT 'Offline',
  last_activity_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  completed_tasks INTEGER DEFAULT 0,
  overdue_tasks INTEGER DEFAULT 0,
  sla_rating NUMERIC DEFAULT 100.0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.audit_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    staff_email TEXT,
    actor_id UUID REFERENCES auth.users(id),
    action TEXT NOT NULL,
    details JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 7. OPERATIONS BOARD (Tasks & Maintenance)
CREATE TABLE IF NOT EXISTS public.admin_tasks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    description TEXT,
    status TEXT DEFAULT 'Todo', -- Todo, InProgress, Review, Done
    priority TEXT DEFAULT 'Medium', -- Low, Medium, High, Critical
    assigned_to TEXT,
    created_by TEXT,
    due_date TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 8. CUSTOMER INTELLIGENCE & ABANDONMENT
CREATE TABLE IF NOT EXISTS public.customer_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID,
    anonymous_id TEXT,
    source_channel TEXT,
    campaign_id TEXT,
    attribution_id TEXT,
    content_variant TEXT,
    entry_page TEXT,
    exit_page TEXT,
    device_info JSONB DEFAULT '{}'::JSONB,
    total_dwell_time_sec INTEGER DEFAULT 0,
    is_converted BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 9. UNIFIED ANALYTICS (Behavioral Timeline)
CREATE TABLE IF NOT EXISTS public.analytics_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_name TEXT NOT NULL, -- e.g., 'PRODUCT_VIEW', 'CHECKOUT_START'
    user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    anonymous_id TEXT,
    session_id TEXT,
    payload JSONB DEFAULT '{}'::JSONB,
    source TEXT DEFAULT 'WEB',
    campaign_id TEXT,
    page_url TEXT,
    device_category TEXT,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_analytics_event_name ON public.analytics_events(event_name);
CREATE INDEX IF NOT EXISTS idx_analytics_timestamp ON public.analytics_events(timestamp DESC);

CREATE TABLE IF NOT EXISTS public.session_forensics (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    session_id UUID REFERENCES public.customer_sessions(id) ON DELETE CASCADE,
    action_type TEXT NOT NULL,
    page_url TEXT,
    metadata JSONB DEFAULT '{}'::JSONB,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.abandoned_carts (
    customer_phone TEXT PRIMARY KEY,
    customer_name TEXT,
    cart_items JSONB,
    total_price NUMERIC,
    session_id TEXT,
    recovery_status TEXT DEFAULT 'Waiting',
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 9. MARKETING & GROWTH
CREATE TABLE IF NOT EXISTS public.coupons (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    code TEXT UNIQUE NOT NULL,
    discount_percent INTEGER NOT NULL,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.ad_campaigns (
    id TEXT PRIMARY KEY,
    product_name TEXT NOT NULL,
    spend NUMERIC DEFAULT 0,
    roas NUMERIC DEFAULT 0,
    clicks INTEGER DEFAULT 0,
    conversions INTEGER DEFAULT 0,
    status TEXT DEFAULT 'Optimizing',
    velocity TEXT DEFAULT 'Stable'
);

CREATE TABLE IF NOT EXISTS public.admin_vault (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    size TEXT,
    authorized_by TEXT,
    storage_path TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.newsletter_subscribers (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.user_consent (
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    anonymous_id TEXT,
    necessary BOOLEAN DEFAULT true,
    analytics BOOLEAN DEFAULT false,
    personalization BOOLEAN DEFAULT false,
    marketing BOOLEAN DEFAULT false,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.data_quality_alerts (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    issue_type TEXT NOT NULL,
    severity TEXT DEFAULT 'Warning',
    description TEXT,
    affected_count INTEGER,
    status TEXT DEFAULT 'OPEN',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.affiliate_payouts (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    profile_id UUID REFERENCES public.profiles(id),
    amount NUMERIC NOT NULL,
    status TEXT DEFAULT 'Pending', -- Pending, Approved, Paid, Rejected
    payment_method TEXT DEFAULT 'M-Pesa',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 10. SUPPORT, REVIEWS & EVENTS
CREATE TABLE IF NOT EXISTS public.events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    description TEXT,
    location_name TEXT NOT NULL, -- e.g. 'Westlands'
    venue_name TEXT,
    event_date TIMESTAMP WITH TIME ZONE NOT NULL,
    interest_count INTEGER DEFAULT 0,
    media_url TEXT,
    is_partner_event BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.support_tickets (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    customer_name TEXT,
    customer_email TEXT,
    subject TEXT,
    description TEXT,
    status TEXT DEFAULT 'Open',
    priority TEXT DEFAULT 'Medium',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.reviews (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  customer_name TEXT NOT NULL,
  rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment TEXT,
  is_hidden BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 11. ANALYTICS & PULSE
CREATE TABLE IF NOT EXISTS public.active_visitors (
  session_id TEXT PRIMARY KEY,
  customer_name TEXT,
  current_page TEXT,
  last_active_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  cart_value NUMERIC DEFAULT 0,
  latitude NUMERIC,
  longitude NUMERIC,
  status TEXT DEFAULT 'Browsing'
);

CREATE TABLE IF NOT EXISTS public.neighborhood_trends (
    zone_name TEXT PRIMARY KEY,
    active_visitors INTEGER DEFAULT 0,
    active_orders INTEGER DEFAULT 0,
    status TEXT DEFAULT 'Quiet'
);

-- 12. BUZZ ENGINE (City Pulse)
CREATE OR REPLACE VIEW public.buzz_metrics AS
SELECT
    zone_name,
    active_visitors,
    active_orders,
    (active_visitors * 0.4 + active_orders * 0.6) as buzz_score,
    CASE
        WHEN (active_visitors * 0.4 + active_orders * 0.6) > 80 THEN 'BUZZING'
        WHEN (active_visitors * 0.4 + active_orders * 0.6) > 50 THEN 'BUSY'
        WHEN (active_visitors * 0.4 + active_orders * 0.6) > 20 THEN 'ACTIVE'
        ELSE 'QUIET'
    END as buzz_status
FROM public.neighborhood_trends;

-- 13. TRIGGERS & AUTOMATION

-- A. Auth to Profile Sync (Idempotent Hardening)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, phone_number, address)
  VALUES (
    new.id,
    new.email,
    NULLIF(new.raw_user_meta_data->>'full_name', ''),
    NULLIF(new.raw_user_meta_data->>'phone_number', ''),
    NULLIF(new.raw_user_meta_data->>'address', '')
  )
  ON CONFLICT (id) DO UPDATE SET
    email = EXCLUDED.email,
    full_name = COALESCE(public.profiles.full_name, EXCLUDED.full_name),
    phone_number = COALESCE(public.profiles.phone_number, EXCLUDED.phone_number),
    address = COALESCE(public.profiles.address, EXCLUDED.address);
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- B. Sync Ledger Balance
CREATE OR REPLACE FUNCTION public.sync_ledger_balance()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE public.ledger_accounts
    SET balance = balance + NEW.amount
    WHERE id = NEW.account_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tr_sync_balance ON public.ledger_entries;
CREATE TRIGGER tr_sync_balance
AFTER INSERT ON public.ledger_entries
FOR EACH ROW EXECUTE PROCEDURE public.sync_ledger_balance();

-- 13. SEED DATA
INSERT INTO public.ledger_accounts (id, name, type)
VALUES
('1000', 'M-Pesa Clearing', 'ASSET'),
('1200', 'Inventory Value', 'ASSET'),
('4000', 'Bar Revenue', 'REVENUE'),
('5000', 'Bar COGS', 'COGS'),
('6300', 'Transaction Fees', 'EXPENSE')
ON CONFLICT (id) DO NOTHING;

-- 14. POLICIES (Hardened)
DO $$
BEGIN
    ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.staff ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
EXCEPTION WHEN others THEN NULL; END $$;

DROP POLICY IF EXISTS "Admins have full access" ON public.products;
CREATE POLICY "Admins have full access" ON public.products FOR ALL TO authenticated USING (true);

DROP POLICY IF EXISTS "Public Read Products" ON public.products;
CREATE POLICY "Public Read Products" ON public.products FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admins manage staff" ON public.staff;
CREATE POLICY "Admins manage staff" ON public.staff FOR ALL TO authenticated USING (true);

DROP POLICY IF EXISTS "Admins manage settings" ON public.settings;
CREATE POLICY "Admins manage settings" ON public.settings FOR ALL TO authenticated USING (true);

DROP POLICY IF EXISTS "Public view settings" ON public.settings;
CREATE POLICY "Public view settings" ON public.settings FOR SELECT TO anon, authenticated USING (is_published = true);
