-- ONLINE BAR: MASTER OS DATASTORE
-- Establishes the unified data layer for Identity, Consent, Analytics, and Experimentation.

-- 1. CONSENT & PRIVACY
CREATE TABLE IF NOT EXISTS public.user_consent (
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    anonymous_id TEXT, -- For guests
    necessary BOOLEAN DEFAULT true,
    analytics BOOLEAN DEFAULT false,
    personalization BOOLEAN DEFAULT false,
    marketing BOOLEAN DEFAULT false,
    policy_version TEXT DEFAULT '1.0',
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    PRIMARY KEY (user_id)
);
CREATE INDEX IF NOT EXISTS idx_consent_anon ON public.user_consent(anonymous_id);

-- 2. UNIFIED ANALYTICS (Behavioral Timeline)
CREATE TABLE IF NOT EXISTS public.analytics_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_name TEXT NOT NULL, -- e.g., 'PRODUCT_VIEWED', 'CHECKOUT_STARTED'
    user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    anonymous_id TEXT,
    session_id TEXT,
    payload JSONB DEFAULT '{}'::JSONB,
    source TEXT DEFAULT 'WEB', -- 'WEB', 'ANDROID', 'SYSTEM'
    campaign_id TEXT, -- Attribution link
    page_url TEXT,
    device_category TEXT, -- 'MOBILE', 'DESKTOP'
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Indexing for journey reconstruction and attribution
CREATE INDEX IF NOT EXISTS idx_analytics_user ON public.analytics_events(user_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_analytics_anon ON public.analytics_events(anonymous_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_analytics_campaign ON public.analytics_events(campaign_id);

-- 3. CUSTOMER SEGMENTS (Dynamic Groups)
CREATE TABLE IF NOT EXISTS public.customer_segments (
    id TEXT PRIMARY KEY, -- e.g., 'DORMANT_VIP', 'CART_ABANDONERS'
    name TEXT NOT NULL,
    description TEXT,
    rule_logic JSONB NOT NULL,
    member_count INTEGER DEFAULT 0,
    last_computed_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS public.user_segment_membership (
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    segment_id TEXT REFERENCES public.customer_segments(id) ON DELETE CASCADE,
    joined_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    PRIMARY KEY (user_id, segment_id)
);

-- 4. EXPERIMENT LAB (A/B Testing Framework)
CREATE TABLE IF NOT EXISTS public.experiments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    hypothesis TEXT,
    status TEXT DEFAULT 'DRAFT', -- 'DRAFT', 'RUNNING', 'COMPLETED', 'ARCHIVED'
    start_date TIMESTAMP WITH TIME ZONE,
    end_date TIMESTAMP WITH TIME ZONE,
    winning_variant_id UUID,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.experiment_variants (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    experiment_id UUID REFERENCES public.experiments(id) ON DELETE CASCADE,
    key TEXT NOT NULL, -- 'A', 'B', 'CONTROL'
    label TEXT NOT NULL,
    config JSONB DEFAULT '{}'::JSONB, -- UI diffs
    reach_count INTEGER DEFAULT 0,
    conversion_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 5. DATA GOVERNANCE & QUALITY
CREATE TABLE IF NOT EXISTS public.data_quality_alerts (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    issue_type TEXT NOT NULL, -- 'ORPHAN_EVENT', 'MISSING_ID', 'ATTRIBUTION_GAP'
    severity TEXT DEFAULT 'Warning',
    description TEXT,
    affected_count INTEGER,
    status TEXT DEFAULT 'OPEN',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 6. SECURITY (RLS)
ALTER TABLE public.user_consent ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.analytics_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_segments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.experiments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users manage own consent" ON public.user_consent FOR ALL USING (auth.uid() = user_id OR (anonymous_id IS NOT NULL AND user_id IS NULL));
CREATE POLICY "Admins view all analytics" ON public.analytics_events FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admins manage segments" ON public.customer_segments FOR ALL TO authenticated USING (true);
CREATE POLICY "Admins manage experiments" ON public.experiments FOR ALL TO authenticated USING (true);
