-- ONLINE BAR: BLACK BOX OBSERVABILITY & AUDIT SCHEMA
-- Evolves the system with high-fidelity logging and distributed tracing.

-- 1. DEEP AUDIT LOGS (Accountability Layer)
ALTER TABLE public.audit_logs
ADD COLUMN IF NOT EXISTS actor_id UUID REFERENCES auth.users(id),
ADD COLUMN IF NOT EXISTS resource_type TEXT, -- 'ORDER', 'PRODUCT', 'MERCHANT', 'SETTING'
ADD COLUMN IF NOT EXISTS resource_id TEXT,
ADD COLUMN IF NOT EXISTS old_value JSONB,
ADD COLUMN IF NOT EXISTS new_value JSONB,
ADD COLUMN IF NOT EXISTS correlation_id TEXT,
ADD COLUMN IF NOT EXISTS request_id TEXT;

-- 2. REQUEST TRACES (Observability Layer)
CREATE TABLE IF NOT EXISTS public.request_traces (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    correlation_id TEXT NOT NULL,
    node_name TEXT NOT NULL, -- 'API', 'DATABASE', 'WHATSAPP', 'META'
    operation TEXT NOT NULL, -- 'FETCH_ORDER', 'PROCESS_PAYMENT'
    duration_ms INTEGER,
    status TEXT DEFAULT 'OK',
    error_details TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 3. METRICS SNAPSHOTS (Analytics Layer)
CREATE TABLE IF NOT EXISTS public.metrics_snapshots (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    metric_name TEXT NOT NULL, -- 'ORDERS_PER_MIN', 'PAYMENT_SUCCESS_RATE'
    metric_value NUMERIC NOT NULL,
    tags JSONB DEFAULT '{}'::JSONB,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Indexing for high-speed historical replay and tracing
CREATE INDEX IF NOT EXISTS idx_traces_correlation ON public.request_traces(correlation_id);
CREATE INDEX IF NOT EXISTS idx_audit_correlation ON public.audit_logs(correlation_id);
CREATE INDEX IF NOT EXISTS idx_audit_resource ON public.audit_logs(resource_type, resource_id);

-- 4. SECURITY (Tamper-Proofing)
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.request_traces ENABLE ROW LEVEL SECURITY;

-- Block DELETES on audit_logs for everyone (including owners) to maintain chain of custody
DROP POLICY IF EXISTS "No deletes on audit" ON public.audit_logs;
CREATE POLICY "No deletes on audit" ON public.audit_logs
FOR DELETE USING (false);

-- Admins can read everything
DROP POLICY IF EXISTS "Admins view audit" ON public.audit_logs;
CREATE POLICY "Admins view audit" ON public.audit_logs
FOR SELECT TO authenticated USING (true);

-- 5. CORRELATION TRIGGER
-- Ensures every new order gets a unique correlation ID if not provided
CREATE OR REPLACE FUNCTION public.assign_correlation_id()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.correlation_id IS NULL THEN
        NEW.correlation_id = 'CORR-' || upper(substring(gen_random_uuid()::text from 1 for 8));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS correlation_id TEXT;
DROP TRIGGER IF EXISTS tr_order_correlation ON public.orders;
CREATE TRIGGER tr_order_correlation
BEFORE INSERT ON public.orders
FOR EACH ROW EXECUTE PROCEDURE public.assign_correlation_id();
