-- ONLINE BAR: CONTENT COMMAND CORE
-- Professional multi-channel publishing infrastructure.

-- 1. CONTENT MASTER (The Source)
CREATE TABLE IF NOT EXISTS public.content_master (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    base_description TEXT,
    media_urls TEXT[] DEFAULT ARRAY[]::TEXT[],
    product_ids BIGINT[],
    buzz_id UUID REFERENCES public.buzz_posts(id),
    status TEXT DEFAULT 'PENDING_REVIEW', -- 'DRAFT', 'PENDING_REVIEW', 'APPROVED', 'ARCHIVED'
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. CONTENT PLATFORM VARIANTS (Adaptations)
CREATE TABLE IF NOT EXISTS public.content_variants (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    master_id UUID REFERENCES public.content_master(id) ON DELETE CASCADE,
    platform TEXT NOT NULL, -- 'INSTAGRAM', 'TIKTOK', 'X', 'WHATSAPP', 'YOUTUBE', 'LINKEDIN', 'PINTEREST'

    caption TEXT,
    headline TEXT,
    cta_url TEXT,

    platform_settings JSONB DEFAULT '{}'::JSONB, -- Aspect ratio, tags, etc.
    status TEXT DEFAULT 'DRAFT',

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. PUBLISHING QUEUE (Jobs)
CREATE TABLE IF NOT EXISTS public.publishing_queue (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    master_id UUID REFERENCES public.content_master(id) ON DELETE CASCADE,
    variant_id UUID REFERENCES public.content_variants(id) ON DELETE CASCADE,
    account_id UUID REFERENCES public.social_accounts(id),

    scheduled_at TIMESTAMPTZ NOT NULL,
    published_at TIMESTAMPTZ,

    status TEXT DEFAULT 'SCHEDULED', -- 'SCHEDULED', 'PUBLISHING', 'SUCCESS', 'FAILED', 'RETRYING'
    attempt_count INTEGER DEFAULT 0,
    last_error TEXT,
    external_post_id TEXT, -- ID from the platform

    attribution_id TEXT DEFAULT gen_random_uuid()::text,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. CONTENT AUDIT LOG
CREATE TABLE IF NOT EXISTS public.content_audit_log (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    content_id UUID,
    actor_email TEXT,
    action TEXT NOT NULL, -- 'CREATE', 'EDIT', 'PUBLISH', 'DELETE', 'RETRY'
    platform TEXT,
    metadata JSONB DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. RLS
ALTER TABLE public.content_master ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.content_variants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.publishing_queue ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.content_audit_log ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins manage content master" ON public.content_master FOR ALL TO authenticated USING (true);
CREATE POLICY "Admins manage variants" ON public.content_variants FOR ALL TO authenticated USING (true);
CREATE POLICY "Admins manage queue" ON public.publishing_queue FOR ALL TO authenticated USING (true);
CREATE POLICY "Admins view audit" ON public.content_audit_log FOR SELECT TO authenticated USING (true);

-- 6. TRIGGER for updated_at
CREATE TRIGGER update_content_master_updated_at
    BEFORE UPDATE ON public.content_master
    FOR EACH ROW
    EXECUTE PROCEDURE update_updated_at_column();

CREATE TRIGGER update_content_variants_updated_at
    BEFORE UPDATE ON public.content_variants
    FOR EACH ROW
    EXECUTE PROCEDURE update_updated_at_column();
