-- ONLINE BAR: FINANCIAL OPERATING SYSTEM (FINANCE OS)
-- Comprehensive architecture for accounting-grade integrity.

-- 1. CHART OF ACCOUNTS (Expanded)
CREATE TABLE IF NOT EXISTS public.chart_of_accounts (
    account_code TEXT PRIMARY KEY, -- e.g., '1000', '2000'
    name TEXT NOT NULL,
    category TEXT NOT NULL, -- 'ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'COGS', 'EXPENSE'
    description TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Seed Initial Chart of Accounts
INSERT INTO public.chart_of_accounts (account_code, name, category)
VALUES
('1000', 'Cash / M-Pesa Clearing', 'ASSET'),
('1100', 'Bank Account', 'ASSET'),
('1200', 'Inventory On Hand', 'ASSET'),
('1300', 'Accounts Receivable', 'ASSET'),
('2000', 'Accounts Payable', 'LIABILITY'),
('2100', 'VAT Payable', 'LIABILITY'),
('2200', 'Excise Duty Payable', 'LIABILITY'),
('3000', 'Owner Equity', 'EQUITY'),
('4000', 'Sales Revenue - Alcohol', 'REVENUE'),
('4100', 'Sales Revenue - Snacks', 'REVENUE'),
('4200', 'Delivery Revenue', 'REVENUE'),
('5000', 'COGS - Alcohol', 'COGS'),
('5100', 'COGS - Snacks', 'COGS'),
('6000', 'Operational Expenses', 'EXPENSE'),
('6100', 'Marketing Spend', 'EXPENSE'),
('6200', 'Rider Commissions', 'EXPENSE'),
('6300', 'Payment Processing Fees', 'EXPENSE')
ON CONFLICT (account_code) DO NOTHING;

-- 2. TAX CONFIGURATIONS (Versioned)
CREATE TABLE IF NOT EXISTS public.tax_configurations (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tax_name TEXT NOT NULL, -- 'VAT', 'EXCISE'
    rate_percent NUMERIC NOT NULL,
    tariff_code TEXT,
    effective_from TIMESTAMP WITH TIME ZONE DEFAULT now(),
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Seed Default KRA Rates
INSERT INTO public.tax_configurations (tax_name, rate_percent, tariff_code)
VALUES
('VAT', 16.0, '2204.00.00'), -- Standard Beverage VAT
('EXCISE_WINE', 25.0, '2204.21.00') -- Sample Excise for Wine
ON CONFLICT DO NOTHING;

-- 3. INVOICES & CREDIT NOTES
CREATE TABLE IF NOT EXISTS public.invoices (
    id TEXT PRIMARY KEY, -- OB-INV-{Number}
    order_id BIGINT REFERENCES public.orders(id) ON DELETE SET NULL,
    customer_id UUID REFERENCES public.profiles(id),
    taxable_amount NUMERIC NOT NULL,
    vat_amount NUMERIC NOT NULL,
    excise_amount NUMERIC DEFAULT 0,
    total_amount NUMERIC NOT NULL,
    etims_ref TEXT,
    status TEXT DEFAULT 'ISSUED', -- 'ISSUED', 'PAID', 'CANCELLED', 'REFUNDED'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.credit_notes (
    id TEXT PRIMARY KEY, -- OB-CN-{Number}
    original_invoice_id TEXT REFERENCES public.invoices(id),
    amount NUMERIC NOT NULL,
    reason TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 4. STOCK MOVEMENTS (Auditable Inventory)
CREATE TABLE IF NOT EXISTS public.stock_movements (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    movement_type TEXT NOT NULL, -- 'PURCHASE', 'SALE', 'DAMAGE', 'RETURN', 'ADJUSTMENT'
    quantity INTEGER NOT NULL, -- Positive for In, Negative for Out
    unit_cost NUMERIC,
    reference_id TEXT, -- Order ID or PO ID
    warehouse_location TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 5. BANK & M-PESA STATEMENTS (Reconciliation Staging)
CREATE TABLE IF NOT EXISTS public.reconciliation_staging (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    transaction_ref TEXT UNIQUE NOT NULL, -- M-Pesa Code or Bank Ref
    source TEXT NOT NULL, -- 'MPESA', 'BANK'
    amount NUMERIC NOT NULL,
    transacted_at TIMESTAMP WITH TIME ZONE NOT NULL,
    description TEXT,
    is_matched BOOLEAN DEFAULT false,
    matched_order_id BIGINT REFERENCES public.orders(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 6. SECURITY: RLS FOR FINANCE
ALTER TABLE public.chart_of_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tax_configurations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reconciliation_staging ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins manage finance" ON public.chart_of_accounts FOR ALL TO authenticated USING (true);
CREATE POLICY "Admins manage tax" ON public.tax_configurations FOR ALL TO authenticated USING (true);
CREATE POLICY "Admins manage invoices" ON public.invoices FOR ALL TO authenticated USING (true);
CREATE POLICY "Admins manage stock ledger" ON public.stock_movements FOR ALL TO authenticated USING (true);
CREATE POLICY "Admins manage recon" ON public.reconciliation_staging FOR ALL TO authenticated USING (true);
