-- ONLINE BAR: CUSTOMER INTELLIGENCE & BEHAVIORAL OS CORE
-- Enabling deep forensics and predictive intent scoring.

-- 1. ENHANCED SESSIONS
CREATE TABLE IF NOT EXISTS public.customer_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id),
    anonymous_id TEXT,
    source_channel TEXT, -- Instagram, Google, Direct
    device_info JSONB,
    entry_page TEXT,
    exit_page TEXT,
    total_dwell_time_sec INTEGER DEFAULT 0,
    is_converted BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 2. SESSION FORENSICS (The "Line-by-Line" Audit)
CREATE TABLE IF NOT EXISTS public.session_forensics (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    session_id UUID REFERENCES public.customer_sessions(id) ON DELETE CASCADE,
    action_type TEXT NOT NULL, -- 'VIEW', 'CLICK', 'CART_ADD', 'CHECKOUT_START', 'PAYMENT_FAIL'
    page_url TEXT,
    component_id TEXT,
    metadata JSONB DEFAULT '{}'::JSONB,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 3. CUSTOMER INTELLIGENCE PROFILE
CREATE TABLE IF NOT EXISTS public.customer_intelligence (
    user_id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
    intent_score INTEGER DEFAULT 0, -- 0-100
    purchase_probability NUMERIC DEFAULT 0.0,
    churn_risk_score INTEGER DEFAULT 0,
    predicted_next_action TEXT,
    preferred_category TEXT,
    avg_dwell_time_per_visit INTEGER DEFAULT 0,
    last_interaction_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    purchase_intent_rank TEXT DEFAULT 'LOW', -- LOW, MEDIUM, HIGH, VERY_HIGH
    price_sensitivity TEXT DEFAULT 'MEDIUM',
    preferred_communication_channel TEXT DEFAULT 'WhatsApp',
    marketing_consent BOOLEAN DEFAULT true,
    total_refunds_value NUMERIC DEFAULT 0,
    total_discounts_value NUMERIC DEFAULT 0,
    discount_dependency_ratio NUMERIC DEFAULT 0.0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 4. CUSTOMER PRODUCT AFFINITY (The "Layer 4")
CREATE TABLE IF NOT EXISTS public.customer_product_preferences (
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    category_id TEXT,
    affinity_score INTEGER DEFAULT 0, -- 0-100 based on views/purchases
    purchase_count INTEGER DEFAULT 0,
    view_count INTEGER DEFAULT 0,
    last_interaction_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    PRIMARY KEY (user_id, category_id)
);

-- 5. ABANDONMENT FORENSICS
CREATE TABLE IF NOT EXISTS public.abandonment_audit (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    session_id UUID REFERENCES public.customer_sessions(id) ON DELETE CASCADE,
    abandonment_point TEXT, -- 'CART', 'SHIPPING', 'PAYMENT'
    last_action TEXT,
    cart_value NUMERIC,
    failure_reason TEXT, -- e.g. M-Pesa Timeout
    is_recovered BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 6. VIEWS FOR CONVERSION FUNNELS
CREATE OR REPLACE VIEW public.behavioral_funnel_stats AS
SELECT
    COUNT(DISTINCT id) as total_visitors,
    COUNT(DISTINCT id) FILTER (WHERE entry_page IS NOT NULL) as awareness,
    (SELECT COUNT(DISTINCT session_id) FROM public.session_forensics WHERE action_type = 'PRODUCT_VIEW') as consideration,
    (SELECT COUNT(DISTINCT session_id) FROM public.session_forensics WHERE action_type = 'ADD_TO_CART') as desire,
    (SELECT COUNT(DISTINCT session_id) FROM public.session_forensics WHERE action_type = 'CHECKOUT_START') as intent,
    COUNT(DISTINCT id) FILTER (WHERE is_converted = true) as conversion
FROM public.customer_sessions;

-- 7. INTENT SCORING LOGIC (The "Brain")
CREATE OR REPLACE FUNCTION public.calculate_intent_score(p_session_id UUID)
RETURNS INTEGER AS $$
DECLARE
    v_score INTEGER := 0;
BEGIN
    -- Search usage
    v_score := v_score + (SELECT COUNT(*) * 5 FROM public.session_forensics WHERE session_id = p_session_id AND action_type = 'SEARCH');
    -- Product views
    v_score := v_score + (SELECT LEAST(COUNT(*) * 10, 30) FROM public.session_forensics WHERE session_id = p_session_id AND action_type = 'PRODUCT_VIEW');
    -- Cart Additions
    v_score := v_score + (SELECT COUNT(*) * 20 FROM public.session_forensics WHERE session_id = p_session_id AND action_type = 'ADD_TO_CART');
    -- Checkout Start
    v_score := v_score + (SELECT COUNT(*) * 40 FROM public.session_forensics WHERE session_id = p_session_id AND action_type = 'CHECKOUT_START');

    RETURN LEAST(v_score, 100);
END;
$$ LANGUAGE plpgsql;

-- 8. CHURN RISK CALCULATOR (Layer 9)
CREATE OR REPLACE FUNCTION public.calculate_churn_risk(p_user_id UUID)
RETURNS INTEGER AS $$
DECLARE
    v_last_purchase TIMESTAMP WITH TIME ZONE;
    v_risk INTEGER := 0;
BEGIN
    SELECT last_purchase_at INTO v_last_purchase FROM public.profiles WHERE id = p_user_id;

    -- If no purchase, check last interaction
    IF v_last_purchase IS NULL THEN
        SELECT last_interaction_at INTO v_last_purchase FROM public.customer_intelligence WHERE user_id = p_user_id;
    END IF;

    IF v_last_purchase IS NULL THEN RETURN 0; END IF;

    -- High risk if more than 30 days since last activity
    IF v_last_purchase < (NOW() - INTERVAL '30 days') THEN
        v_risk := 80;
    ELSIF v_last_purchase < (NOW() - INTERVAL '14 days') THEN
        v_risk := 40;
    END IF;

    RETURN v_risk;
END;
$$ LANGUAGE plpgsql;

-- 9. RLS SECURITY
ALTER TABLE public.customer_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.session_forensics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_intelligence ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.abandonment_audit ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins manage intelligence" ON public.customer_sessions;
CREATE POLICY "Admins manage intelligence" ON public.customer_sessions FOR ALL TO authenticated USING (true);

DROP POLICY IF EXISTS "Admins manage forensics" ON public.session_forensics;
CREATE POLICY "Admins manage forensics" ON public.session_forensics FOR ALL TO authenticated USING (true);

DROP POLICY IF EXISTS "Admins manage profiles" ON public.customer_intelligence;
CREATE POLICY "Admins manage profiles" ON public.customer_intelligence FOR ALL TO authenticated USING (true);

DROP POLICY IF EXISTS "Admins manage audit" ON public.abandonment_audit;
CREATE POLICY "Admins manage audit" ON public.abandonment_audit FOR ALL TO authenticated USING (true);

-- 10. REAL-TIME TELEMETRY RPCs
CREATE OR REPLACE FUNCTION public.increment_session_dwell_time(sess_id UUID, inc_sec INTEGER)
RETURNS VOID AS $$
BEGIN
    UPDATE public.customer_sessions
    SET total_dwell_time_sec = total_dwell_time_sec + inc_sec,
        updated_at = NOW()
    WHERE id = sess_id;
END;
$$ LANGUAGE plpgsql;
