-- ONLINE BAR: INTELLIGENCE & ATTRIBUTION HARDENING
-- Advanced metrics, behavioral funnels, and revenue attribution.

-- 1. PRODUCT PERFORMANCE NODES (Real-time Aggregates)
CREATE TABLE IF NOT EXISTS public.product_intelligence (
    product_id BIGINT PRIMARY KEY REFERENCES public.products(id) ON DELETE CASCADE,
    total_revenue NUMERIC DEFAULT 0,
    units_sold INTEGER DEFAULT 0,
    view_count INTEGER DEFAULT 0,
    cart_add_count INTEGER DEFAULT 0,
    checkout_start_count INTEGER DEFAULT 0,
    return_count INTEGER DEFAULT 0,
    refund_count INTEGER DEFAULT 0,
    avg_active_time_sec INTEGER DEFAULT 0,
    last_sale_at TIMESTAMP WITH TIME ZONE,
    intelligence_score INTEGER DEFAULT 50, -- 0-100
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 2. ATTRIBUTION LOG (Order Source Tracking)
CREATE TABLE IF NOT EXISTS public.revenue_attribution (
    order_id BIGINT PRIMARY KEY REFERENCES public.orders(id) ON DELETE CASCADE,
    source TEXT NOT NULL, -- e.g. 'Instagram', 'TikTok'
    medium TEXT, -- e.g. 'social', 'email'
    campaign TEXT, -- utm_campaign
    content TEXT, -- utm_content
    utm_id TEXT, -- unique message/post ID
    affiliate_id UUID REFERENCES public.profiles(id),
    device_category TEXT, -- 'Mobile', 'Desktop'
    is_first_purchase BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 3. CUSTOMER JOURNEY TIMELINE (Unified Behavioral Feed)
-- This view/table will consolidate analytics_events for a specific session/user
CREATE OR REPLACE VIEW public.vw_customer_journeys AS
SELECT
    session_id,
    user_id,
    anonymous_id,
    event_name,
    payload,
    timestamp,
    ROW_NUMBER() OVER (PARTITION BY session_id ORDER BY timestamp ASC) as step_sequence
FROM public.analytics_events;

-- 4. FUNNEL INSIGHTS (Computed View)
CREATE OR REPLACE VIEW public.vw_product_funnels AS
SELECT
    product_id,
    view_count,
    cart_add_count,
    checkout_start_count,
    units_sold,
    CASE WHEN view_count > 0 THEN (cart_add_count::FLOAT / view_count) * 100 ELSE 0 END as view_to_cart_rate,
    CASE WHEN cart_add_count > 0 THEN (units_sold::FLOAT / cart_add_count) * 100 ELSE 0 END as cart_to_order_rate,
    CASE WHEN view_count > 0 THEN (units_sold::FLOAT / view_count) * 100 ELSE 0 END as overall_conversion_rate
FROM public.product_intelligence;

-- 5. AUTOMATED ANOMALY DETECTION (Pattern Triggers)
CREATE TABLE IF NOT EXISTS public.intelligence_alerts (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    type TEXT NOT NULL, -- 'LOW_CONVERSION', 'HIGH_DEMAND', 'STOCK_OUT_RISK'
    severity TEXT DEFAULT 'INFO',
    subject_id TEXT, -- Product ID or User ID
    message TEXT NOT NULL,
    metadata JSONB DEFAULT '{}'::JSONB,
    is_resolved BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 6. RPC: Increment Product Intelligence
CREATE OR REPLACE FUNCTION public.track_product_interaction(
    p_id BIGINT,
    metric_type TEXT, -- 'VIEW', 'CART', 'CHECKOUT', 'SALE', 'RETURN'
    p_amount NUMERIC DEFAULT 0
) RETURNS VOID AS $$
BEGIN
    INSERT INTO public.product_intelligence (product_id, view_count, cart_add_count, checkout_start_count, units_sold, total_revenue, last_sale_at)
    VALUES (
        p_id,
        CASE WHEN metric_type = 'VIEW' THEN 1 ELSE 0 END,
        CASE WHEN metric_type = 'CART' THEN 1 ELSE 0 END,
        CASE WHEN metric_type = 'CHECKOUT' THEN 1 ELSE 0 END,
        CASE WHEN metric_type = 'SALE' THEN 1 ELSE 0 END,
        CASE WHEN metric_type = 'SALE' THEN p_amount ELSE 0 END,
        CASE WHEN metric_type = 'SALE' THEN now() ELSE NULL END
    )
    ON CONFLICT (product_id) DO UPDATE SET
        view_count = product_intelligence.view_count + EXCLUDED.view_count,
        cart_add_count = product_intelligence.cart_add_count + EXCLUDED.cart_add_count,
        checkout_start_count = product_intelligence.checkout_start_count + EXCLUDED.checkout_start_count,
        units_sold = product_intelligence.units_sold + EXCLUDED.units_sold,
        total_revenue = product_intelligence.total_revenue + EXCLUDED.total_revenue,
        last_sale_at = CASE WHEN metric_type = 'SALE' THEN EXCLUDED.last_sale_at ELSE product_intelligence.last_sale_at END,
        updated_at = now();
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 7. Security (RLS)
ALTER TABLE public.product_intelligence ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.revenue_attribution ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.intelligence_alerts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins manage intel" ON public.product_intelligence FOR ALL TO authenticated USING (true);
CREATE POLICY "Admins view attribution" ON public.revenue_attribution FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admins manage alerts" ON public.intelligence_alerts FOR ALL TO authenticated USING (true);
