-- ONLINE BAR: ONBOARDING INTELLIGENCE & PREMIUM IDENTITY
-- Tracking the journey from first touch to profile personalization.

-- 1. EXTENDED PROFILES (Interests Node)
ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS interests TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN IF NOT EXISTS onboarding_step TEXT DEFAULT 'INTRO', -- 'INTRO', 'ACCOUNT', 'PERSONALIZE', 'COMPLETE'
ADD COLUMN IF NOT EXISTS preferred_vibe TEXT;

-- 2. ONBOARDING FUNNEL LOG
CREATE TABLE IF NOT EXISTS public.onboarding_funnel_log (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    anonymous_id TEXT,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    step_name TEXT NOT NULL, -- 'START', 'DETAILS_ENTERED', 'OTP_SENT', 'VERIFIED', 'PREFS_SET', 'FINISH'
    metadata JSONB DEFAULT '{}'::JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 3. DEVICE & PERFORMANCE TELEMETRY
-- To catch those Android/mobile conversion gaps
CREATE TABLE IF NOT EXISTS public.performance_telemetry (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    session_id UUID REFERENCES public.customer_sessions(id) ON DELETE CASCADE,
    event_type TEXT NOT NULL, -- 'API_LATENCY', 'RENDER_TIME', 'ERROR'
    duration_ms INTEGER,
    path TEXT,
    error_message TEXT,
    device_info JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 4. RLS
ALTER TABLE public.onboarding_funnel_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.performance_telemetry ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins manage onboarding logs" ON public.onboarding_funnel_log FOR ALL TO authenticated USING (true);
CREATE POLICY "Public insert telemetry" ON public.performance_telemetry FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Admins view telemetry" ON public.performance_telemetry FOR SELECT TO authenticated USING (true);

-- 5. FUNCTION: Onboarding Conversion View
CREATE OR REPLACE VIEW public.vw_onboarding_efficiency AS
SELECT
    step_name,
    COUNT(*) as step_count,
    COUNT(DISTINCT anonymous_id) as unique_visitors
FROM public.onboarding_funnel_log
GROUP BY step_name;
