-- ONLINE BAR: OMNI-CHANNEL PUBLISHING ENGINE
-- Architecture for multi-platform social media orchestration and compliance.

-- 1. SOCIAL ACCOUNTS (Encrypted Credential Storage)
CREATE TABLE IF NOT EXISTS public.social_accounts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    platform TEXT NOT NULL, -- 'META', 'TIKTOK', 'GOOGLE', 'X', 'LINKEDIN', 'WHATSAPP'
    account_name TEXT NOT NULL,
    external_id TEXT UNIQUE, -- Platform-specific ID
    access_token_encrypted TEXT,
    refresh_token_encrypted TEXT,
    token_expires_at TIMESTAMP WITH TIME ZONE,
    status TEXT DEFAULT 'CONNECTED', -- 'CONNECTED', 'DISCONNECTED', 'EXPIRED'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 2. CONTENT MASTER (The Source Object)
CREATE TABLE IF NOT EXISTS public.content_master (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    base_description TEXT,
    media_urls TEXT[] DEFAULT ARRAY[]::TEXT[],
    product_ids BIGINT[] DEFAULT ARRAY[]::BIGINT[],
    campaign_id TEXT,
    status TEXT DEFAULT 'DRAFT', -- 'DRAFT', 'PENDING_REVIEW', 'APPROVED', 'PUBLISHED', 'ARCHIVED'
    compliance_score INTEGER DEFAULT 100,
    created_by UUID REFERENCES auth.users(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 3. CONTENT VARIANTS (Platform-specific adaptations)
CREATE TABLE IF NOT EXISTS public.content_variants (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    master_id UUID REFERENCES public.content_master(id) ON DELETE CASCADE,
    platform TEXT NOT NULL,
    caption TEXT,
    hashtags TEXT[],
    cta_url TEXT,
    metadata JSONB DEFAULT '{}'::JSONB, -- Aspect ratios, specific requirements
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 4. PUBLISHING QUEUE (The Scheduler)
CREATE TABLE IF NOT EXISTS public.publishing_queue (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    master_id UUID REFERENCES public.content_master(id) ON DELETE CASCADE,
    account_id UUID REFERENCES public.social_accounts(id) ON DELETE CASCADE,
    scheduled_at TIMESTAMP WITH TIME ZONE NOT NULL,
    status TEXT DEFAULT 'SCHEDULED', -- 'SCHEDULED', 'PUBLISHING', 'SUCCESS', 'FAILED', 'RETRYING'
    external_post_id TEXT,
    attempt_count INTEGER DEFAULT 0,
    last_error TEXT,
    published_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 5. COMPLIANCE LOG (Kenyan NACADA / Global Rules)
CREATE TABLE IF NOT EXISTS public.compliance_log (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    master_id UUID REFERENCES public.content_master(id) ON DELETE CASCADE,
    rule_key TEXT NOT NULL, -- e.g. 'NO_PROMOTIONAL_PRICING', 'AGE_VERIFIED_CHANNEL'
    result TEXT NOT NULL, -- 'PASS', 'FAIL', 'WARNING'
    reviewer_comment TEXT,
    reviewed_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 6. PERFORMANCE NODES
CREATE TABLE IF NOT EXISTS public.social_metrics (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    queue_id UUID REFERENCES public.publishing_queue(id) ON DELETE CASCADE,
    impressions INTEGER DEFAULT 0,
    reach INTEGER DEFAULT 0,
    engagements INTEGER DEFAULT 0,
    clicks INTEGER DEFAULT 0,
    synced_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 7. SECURITY (RLS)
ALTER TABLE public.social_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.content_master ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.content_variants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.publishing_queue ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.compliance_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.social_metrics ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins manage social accounts" ON public.social_accounts FOR ALL TO authenticated USING (true);
CREATE POLICY "Admins manage content master" ON public.content_master FOR ALL TO authenticated USING (true);
CREATE POLICY "Admins manage content variants" ON public.content_variants FOR ALL TO authenticated USING (true);
CREATE POLICY "Admins manage publishing queue" ON public.publishing_queue FOR ALL TO authenticated USING (true);
CREATE POLICY "Admins manage compliance log" ON public.compliance_log FOR ALL TO authenticated USING (true);
CREATE POLICY "Admins view metrics" ON public.social_metrics FOR SELECT TO authenticated USING (true);

-- Indexing for high-performance scheduling
CREATE INDEX IF NOT EXISTS idx_queue_scheduled ON public.publishing_queue(scheduled_at) WHERE status = 'SCHEDULED';
CREATE INDEX IF NOT EXISTS idx_content_master_status ON public.content_master(status);
