-- ONLINE BAR: MOBILE APP WIDGET COMMAND CENTER
-- Infrastructure for remote-controlled home-screen widgets.

-- 1. MOBILE WIDGET DEFINITIONS
CREATE TABLE IF NOT EXISTS public.mobile_app_widgets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    description TEXT,
    content_type TEXT DEFAULT 'PRODUCT', -- 'PRODUCT', 'TRENDING', 'ANNOUNCEMENT', 'ORDER'
    image_url TEXT,
    product_id BIGINT REFERENCES public.products(id),
    cta_label TEXT DEFAULT 'SHOP NOW',
    deep_link TEXT, -- e.g. 'onbar://product/123'

    -- Status & Scheduling
    status TEXT DEFAULT 'DRAFT', -- 'DRAFT', 'PUBLISHED', 'SCHEDULED', 'INACTIVE'
    priority INTEGER DEFAULT 10,
    version INTEGER DEFAULT 1,

    -- Targeting
    target_segment TEXT DEFAULT 'ALL', -- 'ALL', 'VIP', 'NEW', 'WHISKEY_LOVERS'

    start_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    expires_at TIMESTAMP WITH TIME ZONE,

    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 2. WIDGET ENGAGEMENT (ROI Tracking)
CREATE TABLE IF NOT EXISTS public.mobile_app_widget_stats (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    widget_id UUID REFERENCES public.mobile_app_widgets(id) ON DELETE CASCADE,
    event_type TEXT NOT NULL, -- 'DISPLAY', 'CLICK'
    user_id UUID REFERENCES public.profiles(id),
    device_id TEXT,
    attribution_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 3. Security (RLS)
ALTER TABLE public.mobile_app_widgets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mobile_app_widget_stats ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins manage widgets" ON public.mobile_app_widgets FOR ALL TO authenticated USING (true);
CREATE POLICY "Admins view widget stats" ON public.mobile_app_widget_stats FOR SELECT TO authenticated USING (true);
CREATE POLICY "Public read active widgets" ON public.mobile_app_widgets FOR SELECT USING (status = 'PUBLISHED');

-- 4. Initial Seed
INSERT INTO public.mobile_app_widgets (title, description, content_type, status, target_segment)
VALUES
('🔥 Trending Tonight', 'Discover what Nairobi is drinking right now.', 'TRENDING', 'PUBLISHED', 'ALL'),
('🥂 Member Exclusive', 'VIP Gold selection unlocked. Tap to view.', 'ANNOUNCEMENT', 'DRAFT', 'VIP');
