-- ONLINE BAR: THE BUZZ - LIVE CITY INTELLIGENCE
-- Advanced event/location discovery engine with cinematic media support.

-- 1. BUZZ CATEGORIES (Dynamic Registry)
CREATE TABLE IF NOT EXISTS public.buzz_categories (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    label TEXT UNIQUE NOT NULL,
    icon TEXT, -- Lucide icon name
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 2. BUZZ POSTS (The Discovery Nodes)
CREATE TABLE IF NOT EXISTS public.buzz_posts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    description TEXT,
    category_id UUID REFERENCES public.buzz_categories(id),
    status TEXT DEFAULT 'DRAFT', -- 'DRAFT', 'LIVE', 'TRENDING', 'ENDED', 'ARCHIVED'

    -- Geographical Intelligence
    latitude NUMERIC,
    longitude NUMERIC,
    address TEXT,
    area_zone TEXT, -- e.g. 'Westlands'

    -- Temporal Node
    start_at TIMESTAMP WITH TIME ZONE NOT NULL,
    end_at TIMESTAMP WITH TIME ZONE NOT NULL,

    -- Intelligence Signals
    trend_score INTEGER DEFAULT 0, -- 0-100
    is_featured BOOLEAN DEFAULT false,

    created_by UUID REFERENCES auth.users(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 3. BUZZ MEDIA (Cinematic Assets)
CREATE TABLE IF NOT EXISTS public.buzz_media (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    buzz_id UUID REFERENCES public.buzz_posts(id) ON DELETE CASCADE,
    media_type TEXT NOT NULL, -- 'IMAGE', 'VIDEO'
    url TEXT NOT NULL,
    thumbnail_url TEXT,
    sort_order INTEGER DEFAULT 0,
    caption TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 4. BUZZ ENGAGEMENT (Real-time Signals)
CREATE TABLE IF NOT EXISTS public.buzz_engagement (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    buzz_id UUID REFERENCES public.buzz_posts(id) ON DELETE CASCADE,
    event_type TEXT NOT NULL, -- 'VIEW', 'OPEN', 'SHARE', 'MAP_OPEN', 'DIRECTIONS'
    session_id TEXT,
    user_id UUID REFERENCES public.profiles(id),
    latitude NUMERIC,
    longitude NUMERIC,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 5. Seed Initial Categories
INSERT INTO public.buzz_categories (label, icon)
VALUES
('Nightlife', 'Wine'),
('Music', 'Music'),
('Food', 'Utensils'),
('Markets', 'ShoppingBag'),
('Rooftops', 'Globe'),
('Parties', 'Sparkles')
ON CONFLICT (label) DO NOTHING;

-- 6. Trend Score Automation Function
CREATE OR REPLACE FUNCTION public.calculate_buzz_trend_score(b_id UUID)
RETURNS VOID AS $$
DECLARE
    v_views INTEGER;
    v_actions INTEGER;
    v_score INTEGER;
BEGIN
    SELECT count(*) INTO v_views FROM public.buzz_engagement WHERE buzz_id = b_id AND event_type = 'VIEW';
    SELECT count(*) INTO v_actions FROM public.buzz_engagement WHERE buzz_id = b_id AND event_type IN ('SHARE', 'MAP_OPEN', 'DIRECTIONS');

    -- Algorithm: Actions weighted 3x views
    v_score := LEAST(100, (v_views * 1 + v_actions * 3) / 10);

    UPDATE public.buzz_posts SET trend_score = v_score WHERE id = b_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 7. Security (RLS)
ALTER TABLE public.buzz_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.buzz_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.buzz_media ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.buzz_engagement ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read active buzz" ON public.buzz_posts FOR SELECT USING (status IN ('LIVE', 'TRENDING'));
CREATE POLICY "Admins full control buzz" ON public.buzz_posts FOR ALL TO authenticated USING (true);
CREATE POLICY "Public read categories" ON public.buzz_categories FOR SELECT USING (true);
CREATE POLICY "Public read media" ON public.buzz_media FOR SELECT USING (true);
