-- ONLINE BAR: CUSTOMER 360 AUDIT v4.0
-- Comprehensive behavioral engine for first-party journey auditing.

-- 1. ENHANCED SESSIONS (Pillar 8)
ALTER TABLE public.customer_sessions
ADD COLUMN IF NOT EXISTS total_active_time_sec INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_idle_time_sec INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS pages_viewed INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS products_viewed INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS categories_explored INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS searches_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS clicks_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS max_scroll_depth INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS cart_additions INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS cart_removals INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS checkouts_started INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS rage_clicks_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS dead_clicks_count INTEGER DEFAULT 0;

-- 2. CUSTOMER AGGREGATE METRICS (Pillar 6)
CREATE TABLE IF NOT EXISTS public.customer_aggregate_metrics (
    user_id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
    total_sessions INTEGER DEFAULT 0,
    total_active_time_sec BIGINT DEFAULT 0,
    total_pages_viewed BIGINT DEFAULT 0,
    total_products_viewed BIGINT DEFAULT 0,
    total_categories_explored BIGINT DEFAULT 0,
    total_searches BIGINT DEFAULT 0,
    total_clicks BIGINT DEFAULT 0,
    avg_scroll_depth INTEGER DEFAULT 0,
    total_cart_additions BIGINT DEFAULT 0,
    total_cart_removals BIGINT DEFAULT 0,
    total_checkouts_started BIGINT DEFAULT 0,
    total_rage_clicks BIGINT DEFAULT 0,
    total_dead_clicks BIGINT DEFAULT 0,
    most_visited_category TEXT,
    most_viewed_product_id BIGINT,
    most_searched_term TEXT,
    preferred_device TEXT,
    preferred_browser TEXT,
    top_traffic_source TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 3. JOURNEY EVENT LOG (High-Fidelity)
-- Using existing session_forensics but ensuring it covers the journey.
CREATE INDEX IF NOT EXISTS idx_forensics_session_timestamp ON public.session_forensics(session_id, timestamp ASC);

-- 4. SEARCH INTELLIGENCE (Demand Radar)
CREATE TABLE IF NOT EXISTS public.search_intelligence (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    session_id UUID REFERENCES public.customer_sessions(id) ON DELETE CASCADE,
    search_term TEXT NOT NULL,
    results_count INTEGER DEFAULT 0,
    filters_used JSONB DEFAULT '[]'::JSONB,
    sort_used TEXT,
    clicked_product_id BIGINT,
    is_converted BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 5. AUTOMATED METRIC UPDATER (Trigger)
CREATE OR REPLACE FUNCTION public.sync_customer_aggregate_metrics()
RETURNS trigger AS $$
BEGIN
    INSERT INTO public.customer_aggregate_metrics (user_id)
    VALUES (NEW.user_id)
    ON CONFLICT (user_id) DO UPDATE SET
        total_sessions = (SELECT COUNT(*) FROM public.customer_sessions WHERE user_id = NEW.user_id),
        total_active_time_sec = (SELECT SUM(total_active_time_sec) FROM public.customer_sessions WHERE user_id = NEW.user_id),
        total_pages_viewed = (SELECT SUM(pages_viewed) FROM public.customer_sessions WHERE user_id = NEW.user_id),
        total_products_viewed = (SELECT SUM(products_viewed) FROM public.customer_sessions WHERE user_id = NEW.user_id),
        total_clicks = (SELECT SUM(clicks_count) FROM public.customer_sessions WHERE user_id = NEW.user_id),
        updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 7. REAL-TIME TELEMETRY RPCs
CREATE OR REPLACE FUNCTION public.increment_session_active_time(sess_id UUID, inc_active_ms BIGINT, inc_dwell_ms BIGINT)
RETURNS VOID AS $$
BEGIN
    UPDATE public.customer_sessions
    SET total_active_time_sec = total_active_time_sec + (inc_active_ms / 1000),
        total_dwell_time_sec = total_dwell_time_sec + (inc_dwell_ms / 1000),
        updated_at = NOW()
    WHERE id = sess_id;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.increment_session_metric(sess_id UUID, metric_name TEXT, inc_val INTEGER)
RETURNS VOID AS $$
BEGIN
    EXECUTE format('UPDATE public.customer_sessions SET %I = %I + %L, updated_at = NOW() WHERE id = %L',
        metric_name, metric_name, inc_val, sess_id);
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tr_sync_customer_metrics ON public.customer_sessions;
CREATE TRIGGER tr_sync_customer_metrics
    AFTER UPDATE OF user_id, total_active_time_sec, pages_viewed ON public.customer_sessions
    FOR EACH ROW EXECUTE PROCEDURE public.sync_customer_aggregate_metrics();

-- 6. RPC FOR BATCH UPLOAD (Performance Node)
CREATE OR REPLACE FUNCTION public.log_event_batch(p_events JSONB)
RETURNS VOID AS $$
DECLARE
    v_event JSONB;
BEGIN
    FOR v_event IN SELECT * FROM jsonb_array_elements(p_events)
    LOOP
        INSERT INTO public.session_forensics (
            session_id,
            action_type,
            page_url,
            metadata,
            timestamp
        ) VALUES (
            (v_event->>'session_id')::UUID,
            v_event->>'action_type',
            v_event->>'page_url',
            v_event->'metadata',
            (v_event->>'timestamp')::TIMESTAMP WITH TIME ZONE
        );
    END LOOP;
END;
$$ LANGUAGE plpgsql;

-- 7. REAL-TIME TELEMETRY RPCs
CREATE OR REPLACE FUNCTION public.increment_session_active_time(sess_id UUID, inc_active_ms BIGINT, inc_dwell_ms BIGINT)
RETURNS VOID AS $$
BEGIN
    UPDATE public.customer_sessions
    SET total_active_time_sec = total_active_time_sec + (inc_active_ms / 1000),
        total_dwell_time_sec = total_dwell_time_sec + (inc_dwell_ms / 1000),
        updated_at = NOW()
    WHERE id = sess_id;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.increment_session_metric(sess_id UUID, metric_name TEXT, inc_val INTEGER)
RETURNS VOID AS $$
BEGIN
    EXECUTE format('UPDATE public.customer_sessions SET %I = %I + %L, updated_at = NOW() WHERE id = %L',
        metric_name, metric_name, inc_val, sess_id);
END;
$$ LANGUAGE plpgsql;
