-- ONLINE BAR: MESSAGE COMMAND CENTER & SQL REPAIR
-- Consolidated migration to establish the messaging fortress and fix dependency errors.

-- 1. SOCIAL ACCOUNTS (The External Nodes)
CREATE TABLE IF NOT EXISTS public.social_accounts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    platform TEXT NOT NULL, -- 'META', 'TIKTOK', 'GOOGLE', 'X', 'LINKEDIN', 'WHATSAPP'
    account_name TEXT NOT NULL,
    external_id TEXT UNIQUE,
    status TEXT DEFAULT 'CONNECTED', -- 'CONNECTED', 'DISCONNECTED', 'EXPIRED'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 2. CONTENT MASTER (The Narrative Source)
CREATE TABLE IF NOT EXISTS public.content_master (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    base_description TEXT,
    media_urls TEXT[] DEFAULT ARRAY[]::TEXT[],
    product_ids BIGINT[] DEFAULT ARRAY[]::BIGINT[],
    status TEXT DEFAULT 'DRAFT', -- 'DRAFT', 'PENDING_REVIEW', 'APPROVED', 'PUBLISHED'
    compliance_score INTEGER DEFAULT 100,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 3. CONTENT VARIANTS (Platform-Specific Adaptations)
CREATE TABLE IF NOT EXISTS public.content_variants (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    master_id UUID REFERENCES public.content_master(id) ON DELETE CASCADE,
    platform TEXT NOT NULL,
    caption TEXT,
    cta_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 4. PUBLISHING QUEUE (The Dispatch Job)
CREATE TABLE IF NOT EXISTS public.publishing_queue (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    master_id UUID REFERENCES public.content_master(id) ON DELETE CASCADE,
    account_id UUID REFERENCES public.social_accounts(id) ON DELETE CASCADE,
    scheduled_at TIMESTAMP WITH TIME ZONE NOT NULL,
    status TEXT DEFAULT 'SCHEDULED', -- 'SCHEDULED', 'PUBLISHING', 'SUCCESS', 'FAILED'
    attribution_id TEXT UNIQUE DEFAULT gen_random_uuid()::text,
    external_post_id TEXT,
    last_error TEXT,
    published_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 5. AUDIENCE SEGMENTS (Dynamic Groupings)
CREATE TABLE IF NOT EXISTS public.audience_segments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT UNIQUE NOT NULL,
    description TEXT,
    rule_logic JSONB DEFAULT '{}'::JSONB, -- e.g. {"ltv_min": 50000}
    estimated_reach INTEGER DEFAULT 0,
    is_system_segment BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 6. MESSAGE CAMPAIGNS (Tracking & ROI)
CREATE TABLE IF NOT EXISTS public.message_campaigns (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    type TEXT DEFAULT 'BROADCAST', -- 'BROADCAST', 'JOURNEY', 'TRIGGER'
    audience_id UUID REFERENCES public.audience_segments(id),
    status TEXT DEFAULT 'ACTIVE',
    sent_count INTEGER DEFAULT 0,
    open_count INTEGER DEFAULT 0,
    click_count INTEGER DEFAULT 0,
    attributed_revenue NUMERIC DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 7. COMPLIANCE RULES (Regulatory Registry)
CREATE TABLE IF NOT EXISTS public.compliance_rules (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    rule_name TEXT UNIQUE NOT NULL,
    rule_type TEXT NOT NULL, -- 'BLACKLIST_WORD', 'MANDATORY_DISCLOSURE'
    pattern TEXT NOT NULL,
    replacement_text TEXT,
    severity TEXT DEFAULT 'BLOCK', -- 'BLOCK', 'WARNING'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 8. SECURITY (RLS)
ALTER TABLE public.social_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.content_master ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.publishing_queue ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audience_segments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.message_campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.compliance_rules ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins full control social_accounts" ON public.social_accounts FOR ALL TO authenticated USING (true);
CREATE POLICY "Admins full control content_master" ON public.content_master FOR ALL TO authenticated USING (true);
CREATE POLICY "Admins full control publishing_queue" ON public.publishing_queue FOR ALL TO authenticated USING (true);
CREATE POLICY "Admins full control audience_segments" ON public.audience_segments FOR ALL TO authenticated USING (true);
CREATE POLICY "Admins full control message_campaigns" ON public.message_campaigns FOR ALL TO authenticated USING (true);
CREATE POLICY "Admins full control compliance_rules" ON public.compliance_rules FOR ALL TO authenticated USING (true);

-- 9. Seed Initial Segments
INSERT INTO public.audience_segments (name, description, estimated_reach, is_system_segment)
VALUES
('All Patrons', 'Every verified account on the grid.', 2480, true),
('VIP & Legends', 'High-LTV patrons with Gold/Diamond/Legend rank.', 412, true),
('Inactive (30d)', 'Patrons who haven''t placed an order in the last 30 days.', 184, true),
('Newcomers', 'Users who registered in the last 7 days.', 96, true)
ON CONFLICT (name) DO NOTHING;

-- 10. Seed Compliance
INSERT INTO public.compliance_rules (rule_name, rule_type, pattern, severity, replacement_text)
VALUES
('Universal Disclaimer', 'MANDATORY_DISCLOSURE', 'ALL', 'WARNING', 'Excessive consumption of alcohol is harmful to your health. Strictly 18+ only.')
ON CONFLICT (rule_name) DO NOTHING;
