-- ONLINE BAR: BUZZ COMMAND CORE
-- Advanced city discovery, venue management, and experience orchestration.

-- 1. BUZZ VENUES (Permanent Places)
CREATE TABLE IF NOT EXISTS public.buzz_venues (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT UNIQUE NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    description TEXT,
    category TEXT NOT NULL, -- 'Bar', 'Club', 'Lounge', 'Restaurant', 'Rooftop'

    address TEXT,
    area_id UUID REFERENCES public.pulse_areas(id),

    latitude NUMERIC,
    longitude NUMERIC,

    opening_hours JSONB DEFAULT '{}'::JSONB,
    amenities TEXT[] DEFAULT ARRAY[]::TEXT[], -- ['Parking', 'Security', 'Wi-Fi']
    price_band TEXT DEFAULT '$$', -- '$', '$$', '$$$', '$$$$'

    hero_image_url TEXT,
    gallery_urls TEXT[] DEFAULT ARRAY[]::TEXT[],

    rating NUMERIC DEFAULT 5.0,
    is_verified BOOLEAN DEFAULT false,
    is_active BOOLEAN DEFAULT true,

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. BUZZ EXPERIENCES (Layer C - Moments)
CREATE TABLE IF NOT EXISTS public.buzz_experiences (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    venue_id UUID REFERENCES public.buzz_venues(id) ON DELETE CASCADE,
    title TEXT NOT NULL, -- e.g. 'Live Jazz Night'
    headline TEXT,
    description TEXT,

    start_at TIMESTAMP WITH TIME ZONE NOT NULL,
    end_at TIMESTAMP WITH TIME ZONE NOT NULL,

    status TEXT DEFAULT 'LIVE', -- 'DRAFT', 'LIVE', 'ENDING', 'ARCHIVED'
    category_id UUID REFERENCES public.buzz_categories(id),

    interest_count INTEGER DEFAULT 0,
    confidence_score INTEGER DEFAULT 100,

    is_featured BOOLEAN DEFAULT false,

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. BUZZ SIGNALS (The Intelligence Feed)
CREATE TABLE IF NOT EXISTS public.buzz_signals (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    subject_type TEXT NOT NULL, -- 'VENUE', 'AREA', 'EXPERIENCE'
    subject_id UUID NOT NULL,

    signal_type TEXT NOT NULL, -- 'SEARCH_SPIKE', 'SOCIAL_MOMENTUM', 'VERIFIED_EVENT'
    strength INTEGER DEFAULT 10, -- 0-100

    metadata JSONB DEFAULT '{}'::JSONB,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. RLS
ALTER TABLE public.buzz_venues ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.buzz_experiences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.buzz_signals ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read venues" ON public.buzz_venues FOR SELECT USING (true);
CREATE POLICY "Public read experiences" ON public.buzz_experiences FOR SELECT USING (status = 'LIVE');
CREATE POLICY "Admins manage everything buzz" ON public.buzz_venues FOR ALL TO authenticated USING (true);
CREATE POLICY "Admins manage experiences" ON public.buzz_experiences FOR ALL TO authenticated USING (true);
CREATE POLICY "Admins manage signals" ON public.buzz_signals FOR ALL TO authenticated USING (true);

-- 5. FUNCTION: Calculate Dynamic Buzz Score
CREATE OR REPLACE FUNCTION public.get_area_buzz_score(p_area_id UUID)
RETURNS INTEGER AS $$
DECLARE
    v_score INTEGER := 0;
    v_exp_count INTEGER;
    v_signal_strength INTEGER;
BEGIN
    -- 1. Active Experiences
    SELECT count(*) INTO v_exp_count FROM public.buzz_experiences
    WHERE status = 'LIVE' AND venue_id IN (SELECT id FROM public.buzz_venues WHERE area_id = p_area_id);

    v_score := v_score + (v_exp_count * 15);

    -- 2. Recent Signals
    SELECT coalesce(sum(strength), 0) INTO v_signal_strength FROM public.buzz_signals
    WHERE subject_id = p_area_id AND expires_at > now();

    v_score := v_score + (v_signal_strength / 2);

    RETURN LEAST(v_score, 100);
END;
$$ LANGUAGE plpgsql STABLE;
