-- ONLINE BAR: CITY PULSE CMS CORE
-- Establishes permanent Areas and temporary Pulse Posts logic.

-- 1. Pulse Areas (Neighborhood Nodes)
CREATE TABLE IF NOT EXISTS public.pulse_areas (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    zone_name TEXT UNIQUE NOT NULL, -- e.g. 'Westlands'
    description TEXT,
    hero_image_url TEXT,
    buzz_mode TEXT DEFAULT 'HYBRID', -- 'AUTO', 'MANUAL', 'HYBRID'
    manual_boost INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 2. Pulse Posts (Temporary Moments)
CREATE TABLE IF NOT EXISTS public.pulse_posts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    area_id UUID REFERENCES public.pulse_areas(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    headline TEXT,
    description TEXT,
    status TEXT DEFAULT 'DRAFT', -- 'DRAFT', 'SUBMITTED', 'APPROVED', 'LIVE', 'ENDED', 'ARCHIVED'
    start_time TIMESTAMP WITH TIME ZONE NOT NULL,
    end_time TIMESTAMP WITH TIME ZONE NOT NULL,
    hero_image_url TEXT,
    media_urls TEXT[] DEFAULT ARRAY[]::TEXT[],
    tags TEXT[] DEFAULT ARRAY[]::TEXT[], -- e.g. ['Live Music', 'Tasting']
    cta_label TEXT DEFAULT 'EXPLORE', -- 'EXPLORE', 'VIEW EVENT', 'SHOP THE COLLECTION'
    is_featured BOOLEAN DEFAULT false,
    created_by UUID REFERENCES auth.users(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 3. Pulse Post Product Linking
CREATE TABLE IF NOT EXISTS public.pulse_post_products (
    post_id UUID REFERENCES public.pulse_posts(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    PRIMARY KEY (post_id, product_id)
);

-- 4. Pulse Analytics (Operational Signals)
CREATE TABLE IF NOT EXISTS public.pulse_analytics (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    post_id UUID REFERENCES public.pulse_posts(id) ON DELETE CASCADE,
    view_count INTEGER DEFAULT 0,
    open_count INTEGER DEFAULT 0,
    cta_click_count INTEGER DEFAULT 0,
    conversion_count INTEGER DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 5. Migrate Existing Neighborhoods to Pulse Areas
INSERT INTO public.pulse_areas (zone_name, is_active)
SELECT zone_name, true FROM public.neighborhood_trends
ON CONFLICT (zone_name) DO NOTHING;

-- 6. RLS Hardening
ALTER TABLE public.pulse_areas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pulse_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pulse_post_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pulse_analytics ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Read Areas" ON public.pulse_areas FOR SELECT USING (true);
CREATE POLICY "Public Read Posts" ON public.pulse_posts FOR SELECT USING (status = 'LIVE');
CREATE POLICY "Admins full control areas" ON public.pulse_areas FOR ALL TO authenticated USING (true);
CREATE POLICY "Admins full control posts" ON public.pulse_posts FOR ALL TO authenticated USING (true);
