-- ONLINE BAR: GROWTH AUTOPILOT & COMPLIANCE ENGINE
-- Registry for recurring publishing slots and regulatory compliance rules.

-- 1. AUTOPILOT RULES (Recurring Slots)
CREATE TABLE IF NOT EXISTS public.growth_autopilot_rules (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    slot_day_of_week INTEGER NOT NULL, -- 0-6 (Sunday-Saturday)
    slot_time TIME NOT NULL,
    platform TEXT NOT NULL, -- 'META', 'TIKTOK', 'WHATSAPP'
    content_source TEXT DEFAULT 'TRENDING', -- 'TRENDING', 'NEW_ARRIVALS', 'LOW_STOCK', 'EDITORIAL'
    is_active BOOLEAN DEFAULT true,
    last_generated_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 2. COMPLIANCE RULES (Regulatory Guardrails)
CREATE TABLE IF NOT EXISTS public.compliance_rules (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    rule_name TEXT UNIQUE NOT NULL,
    rule_type TEXT NOT NULL, -- 'BLACKLIST_WORD', 'MANDATORY_DISCLOSURE', 'PLATFORM_RESTRICTION'
    pattern TEXT NOT NULL, -- The word or phrase to match
    replacement_text TEXT, -- For mandatory disclosures
    severity TEXT DEFAULT 'BLOCK', -- 'BLOCK', 'WARNING', 'INFO'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 3. ATTRIBUTION EXTENSION
ALTER TABLE public.publishing_queue
ADD COLUMN IF NOT EXISTS attribution_id TEXT UNIQUE DEFAULT gen_random_uuid()::text;

-- 4. Seed Compliance Rules (Kenyan Context)
INSERT INTO public.compliance_rules (rule_name, rule_type, pattern, severity, replacement_text)
VALUES
('Mandatory Disclosure', 'MANDATORY_DISCLOSURE', 'ALL', 'WARNING', 'Excessive consumption of alcohol is harmful to your health. Strictly 18+ only.'),
('Cheap Claim', 'BLACKLIST_WORD', 'cheap', 'BLOCK', NULL),
('Best Price', 'BLACKLIST_WORD', 'best price', 'WARNING', NULL),
('Unverified Health', 'BLACKLIST_WORD', 'healthy', 'BLOCK', NULL)
ON CONFLICT (rule_name) DO NOTHING;

-- 5. Security (RLS)
ALTER TABLE public.growth_autopilot_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.compliance_rules ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins manage autopilot" ON public.growth_autopilot_rules FOR ALL TO authenticated USING (true);
CREATE POLICY "Admins manage compliance" ON public.compliance_rules FOR ALL TO authenticated USING (true);
