-- ONLINE BAR: GRID ESTABLISHMENT MASTER SCRIPT (HARDENED v1.0)
-- Consolidates all tables, relationships, and RLS policies for a 100% functional bar grid.
-- Run this in your Supabase SQL Editor.

-- 1. CORE IDENTITY & PROFILES
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT,
  full_name TEXT,
  phone_number TEXT UNIQUE,
  address TEXT,
  latitude NUMERIC,
  longitude NUMERIC,
  birth_date DATE,
  referral_code TEXT UNIQUE,
  referral_clicks INTEGER DEFAULT 0,
  loyalty_points INTEGER DEFAULT 0,
  wallet_balance NUMERIC DEFAULT 0,
  total_commission_earned NUMERIC DEFAULT 0,
  status_flag TEXT DEFAULT 'Active',
  current_streak INTEGER DEFAULT 0,
  xp INTEGER DEFAULT 0,
  level INTEGER DEFAULT 1,
  title TEXT DEFAULT 'Newcomer',
  last_streak_update TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 2. PRODUCTS & CELLAR
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  brand TEXT,
  sku TEXT UNIQUE,
  model_number TEXT,
  price NUMERIC NOT NULL,
  old_price NUMERIC,
  cost_price NUMERIC DEFAULT 0,
  description TEXT,
  short_description TEXT,
  what_is_in_the_box TEXT,
  image_url TEXT,
  images TEXT[] DEFAULT ARRAY[]::TEXT[],
  video_url TEXT,
  category TEXT DEFAULT 'wine',
  sub_category TEXT,
  is_snack BOOLEAN DEFAULT false,
  sizes TEXT[] DEFAULT ARRAY['Standard'],
  stock INT DEFAULT 0,
  low_stock_alert INT DEFAULT 5,
  warehouse_location TEXT,
  variant_stock JSONB DEFAULT '{}'::JSONB,
  tech_specs JSONB DEFAULT '{}'::JSONB,
  is_featured BOOLEAN DEFAULT false,
  featured_rank INT DEFAULT 99,
  is_new BOOLEAN DEFAULT true,
  is_best_seller BOOLEAN DEFAULT false,
  allow_backorders BOOLEAN DEFAULT false,
  hide_product BOOLEAN DEFAULT false,
  min_loyalty_tier TEXT DEFAULT 'Explorer',
  is_dynamic_pricing BOOLEAN DEFAULT false,
  price_min NUMERIC,
  price_max NUMERIC,
  wholesale_price NUMERIC,
  wholesale_min_qty INT DEFAULT 10,
  wholesale_stock_reserve INT DEFAULT 0,
  seo_title TEXT,
  seo_description TEXT,
  seo_keywords TEXT[],
  rating NUMERIC DEFAULT 5.0,
  status TEXT DEFAULT 'Live',
  supplier_id BIGINT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 3. ORDERS & DISPATCH
CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  session_id TEXT,
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  customer_email TEXT,
  product_id BIGINT REFERENCES products(id) ON DELETE SET NULL, -- Legacy support
  total_price NUMERIC NOT NULL,
  delivery_cost NUMERIC DEFAULT 0,
  status TEXT DEFAULT 'Created',
  payment_method TEXT DEFAULT 'M-Pesa',
  checkout_request_id TEXT,
  payment_verified_at TIMESTAMP WITH TIME ZONE,
  note TEXT,
  referred_by_code TEXT,
  rider_name TEXT,
  rider_phone TEXT,
  captured_by TEXT DEFAULT 'system',
  latitude NUMERIC,
  longitude NUMERIC,
  warehouse_location TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.order_items (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    quantity INT NOT NULL DEFAULT 1,
    unit_price NUMERIC NOT NULL,
    unit_cost NUMERIC NOT NULL,
    size TEXT DEFAULT 'Standard',
    status TEXT DEFAULT 'Pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 4. RIDER ECOSYSTEM
CREATE TABLE IF NOT EXISTS public.rider_status (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID REFERENCES auth.users(id),
    rider_name TEXT NOT NULL,
    rider_phone TEXT UNIQUE NOT NULL,
    vehicle_type TEXT DEFAULT 'Motorbike',
    vehicle_reg TEXT,
    pin TEXT DEFAULT '1234',
    current_location TEXT,
    status TEXT DEFAULT 'Offline',
    battery_level INTEGER DEFAULT 100,
    total_deliveries INTEGER DEFAULT 0,
    rating DECIMAL DEFAULT 5.0,
    area_zone TEXT DEFAULT 'Nairobi',
    health_score INTEGER DEFAULT 100,
    current_tier TEXT DEFAULT 'Bronze',
    acceptance_rate INTEGER DEFAULT 100,
    online_since TIMESTAMP WITH TIME ZONE,
    biometric_key JSONB,
    verification_status TEXT DEFAULT 'Pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.rider_wallets (
    rider_phone TEXT PRIMARY KEY REFERENCES public.rider_status(rider_phone) ON DELETE CASCADE,
    balance NUMERIC DEFAULT 0,
    total_earned NUMERIC DEFAULT 0,
    last_payout TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 5. STAFF & AUDIT
CREATE TABLE IF NOT EXISTS public.staff (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT UNIQUE NOT NULL,
  role TEXT DEFAULT 'STAFF',
  pin TEXT,
  supplier_id BIGINT,
  status TEXT DEFAULT 'Offline',
  last_activity_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  completed_tasks INTEGER DEFAULT 0,
  overdue_tasks INTEGER DEFAULT 0,
  sla_rating INTEGER DEFAULT 100,
  can_view_revenue BOOLEAN DEFAULT false,
  can_manage_inventory BOOLEAN DEFAULT true,
  can_manage_orders BOOLEAN DEFAULT true,
  can_execute_payouts BOOLEAN DEFAULT false,
  can_view_audit_logs BOOLEAN DEFAULT false,
  can_manage_settings BOOLEAN DEFAULT false,
  can_manage_staff BOOLEAN DEFAULT false,
  can_view_sensitive_data BOOLEAN DEFAULT false,
  can_manage_communications BOOLEAN DEFAULT false,
  can_manage_marketing BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.audit_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    staff_email TEXT,
    actor_id UUID REFERENCES auth.users(id),
    action TEXT NOT NULL,
    details JSONB,
    resource_type TEXT,
    resource_id TEXT,
    old_value JSONB,
    new_value JSONB,
    correlation_id TEXT,
    request_id TEXT,
    ip_address TEXT,
    device_info TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 6. MARKETING & AUTOMATION
CREATE TABLE IF NOT EXISTS public.marketing_campaigns (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    base_message TEXT,
    media_url TEXT,
    cta_link TEXT,
    status TEXT DEFAULT 'DRAFT',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.ad_campaigns (
    id TEXT PRIMARY KEY,
    product_name TEXT NOT NULL,
    spend NUMERIC DEFAULT 0,
    roas NUMERIC DEFAULT 0,
    clicks INTEGER DEFAULT 0,
    conversions INTEGER DEFAULT 0,
    status TEXT DEFAULT 'Optimizing',
    velocity TEXT DEFAULT 'Stable'
);

CREATE TABLE IF NOT EXISTS public.marketing_automations (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    trigger TEXT NOT NULL,
    action TEXT NOT NULL,
    channel TEXT NOT NULL,
    is_active BOOLEAN DEFAULT true,
    runs_count INTEGER DEFAULT 0,
    last_run_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 7. ANALYTICS & LOGS
CREATE TABLE IF NOT EXISTS public.analytics_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_name TEXT NOT NULL,
    user_id UUID REFERENCES auth.users(id),
    anonymous_id TEXT,
    session_id TEXT,
    payload JSONB DEFAULT '{}'::JSONB,
    correlation_id TEXT,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.event_log (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    event_type TEXT NOT NULL,
    payload JSONB,
    user_id UUID,
    metadata JSONB,
    status TEXT DEFAULT 'PENDING',
    processed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.active_visitors (
  session_id TEXT PRIMARY KEY,
  customer_name TEXT,
  current_page TEXT,
  last_active_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  cart_value NUMERIC DEFAULT 0,
  latitude NUMERIC,
  longitude NUMERIC,
  status TEXT DEFAULT 'Browsing'
);

-- 8. SETTINGS & SYSTEM
CREATE TABLE IF NOT EXISTS public.settings (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL,
    is_published BOOLEAN DEFAULT true,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 9. PARTNERS (Vendors & Suppliers)
CREATE TABLE IF NOT EXISTS public.marketplace_vendors (
    id TEXT PRIMARY KEY DEFAULT 'v' || floor(random() * 1000000)::text,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    status TEXT DEFAULT 'Pending',
    sales_total NUMERIC DEFAULT 0,
    items_count INTEGER DEFAULT 0,
    commission_rate NUMERIC DEFAULT 10,
    merchant_level INTEGER DEFAULT 1,
    merchant_xp INTEGER DEFAULT 0,
    joined_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.suppliers (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID REFERENCES auth.users(id),
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    phone TEXT,
    rating NUMERIC DEFAULT 100,
    is_active BOOLEAN DEFAULT false,
    verification_status TEXT DEFAULT 'Pending',
    business_permit_url TEXT,
    kra_pin_url TEXT,
    premises_license_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 10. REVIEWS & MESSAGES
CREATE TABLE IF NOT EXISTS public.reviews (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
  customer_name TEXT NOT NULL,
  customer_phone TEXT,
  rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment TEXT,
  photo_urls TEXT[] DEFAULT ARRAY[]::TEXT[],
  is_verified_owner BOOLEAN DEFAULT false,
  is_hidden BOOLEAN DEFAULT false,
  admin_response TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.messages (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  subject TEXT DEFAULT 'In-App Support Ticket',
  message TEXT NOT NULL,
  status TEXT DEFAULT 'New',
  admin_response TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 11. FINANCE & LEDGER
CREATE TABLE IF NOT EXISTS public.financial_ledger (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE SET NULL,
    entry_type TEXT NOT NULL, -- 'REVENUE', 'SUPPLIER_PAYABLE', 'DELIVERY_FEE', 'PAYMENT_FEE', 'EXPENSE'
    amount NUMERIC NOT NULL,
    description TEXT,
    is_reconciled BOOLEAN DEFAULT false,
    metadata JSONB DEFAULT '{}'::JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.loyalty_ledger (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    amount INTEGER NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 12. LOGISTICS
CREATE TABLE IF NOT EXISTS public.shipments (
    id TEXT PRIMARY KEY,
    origin TEXT,
    method TEXT, -- 'Sea', 'Air'
    status TEXT, -- 'In Transit', 'Clearing', 'Delivered', 'Pending'
    eta TEXT,
    value_usd NUMERIC,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.delivery_statistics (
    order_id BIGINT PRIMARY KEY REFERENCES public.orders(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE,
    paid_at TIMESTAMP WITH TIME ZONE,
    accepted_at TIMESTAMP WITH TIME ZONE,
    prep_completed_at TIMESTAMP WITH TIME ZONE,
    dispatched_at TIMESTAMP WITH TIME ZONE,
    picked_up_at TIMESTAMP WITH TIME ZONE,
    delivered_at TIMESTAMP WITH TIME ZONE,
    prep_time_min INTEGER,
    travel_time_min INTEGER,
    total_time_min INTEGER,
    delay_min INTEGER,
    delay_reason TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 13. INDEXING
CREATE INDEX IF NOT EXISTS idx_analytics_event_name ON public.analytics_events(event_name);
CREATE INDEX IF NOT EXISTS idx_analytics_user_id ON public.analytics_events(user_id);
CREATE INDEX IF NOT EXISTS idx_analytics_anon_id ON public.analytics_events(anonymous_id);
CREATE INDEX IF NOT EXISTS idx_orders_customer_phone ON public.orders(customer_phone);
CREATE INDEX IF NOT EXISTS idx_products_is_snack ON public.products(is_snack);

-- 14. OBSERVABILITY & SECURITY
CREATE TABLE IF NOT EXISTS public.request_traces (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    correlation_id TEXT,
    node_name TEXT, -- 'API', 'DATABASE', etc.
    operation TEXT,
    duration_ms INTEGER,
    status TEXT, -- 'OK', 'ERROR'
    error_details TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.metrics_snapshots (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    metric_name TEXT NOT NULL,
    metric_value NUMERIC NOT NULL,
    tags JSONB DEFAULT '{}'::JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.security_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id),
    event_type TEXT NOT NULL,
    severity TEXT,
    ip_address TEXT,
    device_fingerprint TEXT,
    risk_score_delta INTEGER DEFAULT 0,
    details JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.ip_blacklist (
    ip_address TEXT PRIMARY KEY,
    reason TEXT,
    banned_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.exception_log (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    type TEXT NOT NULL,
    severity TEXT, -- 'Warning', 'Critical'
    details JSONB,
    status TEXT DEFAULT 'Open', -- 'Open', 'Resolved'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.automation_runs (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    rule_id TEXT,
    event_id TEXT,
    status TEXT, -- 'EXECUTED', 'FAILED', etc.
    errors TEXT,
    executed_actions JSONB DEFAULT '[]'::JSONB,
    executed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.system_autonomous_state (
    engine_name TEXT PRIMARY KEY,
    is_autonomous BOOLEAN DEFAULT true,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 15. ROW LEVEL SECURITY (RLS) - Basic Public Read
DO $$
BEGIN
    ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
EXCEPTION
    WHEN others THEN NULL;
END $$;

DROP POLICY IF EXISTS "Public Read Products" ON public.products;
CREATE POLICY "Public Read Products" ON public.products FOR SELECT USING (true);

-- 16. TRUST PASSPORT SYSTEM
CREATE TABLE IF NOT EXISTS public.bottle_passports (
    id TEXT PRIMARY KEY, -- cryptographically random ID
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    batch_number TEXT,
    manufactured_at TIMESTAMP WITH TIME ZONE,
    origin_manufacturer TEXT,
    authorized_distributor TEXT,
    current_status TEXT DEFAULT 'Verified', -- 'Verified', 'Flagged', 'Compromised'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.bottle_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    bottle_id TEXT REFERENCES public.bottle_passports(id) ON DELETE CASCADE,
    event_type TEXT NOT NULL, -- 'MANUFACTURED', 'DISTRIBUTED', 'RECEIVED', 'SOLD', 'VERIFIED'
    location_label TEXT,
    actor_label TEXT,
    metadata JSONB DEFAULT '{}'::JSONB,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.verification_scans (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    bottle_id TEXT REFERENCES public.bottle_passports(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    ip_address TEXT,
    city_coarse TEXT,
    device_info TEXT,
    is_anomaly BOOLEAN DEFAULT false,
    anomaly_reason TEXT,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.trust_alerts (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    bottle_id TEXT REFERENCES public.bottle_passports(id),
    severity TEXT DEFAULT 'Warning', -- 'Warning', 'Critical'
    description TEXT,
    status TEXT DEFAULT 'OPEN',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 17. MARKETING ORCHESTRATOR v2
CREATE TABLE IF NOT EXISTS public.marketing_campaigns_v2 (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    product_id BIGINT REFERENCES public.products(id),
    base_message TEXT,
    media_url TEXT,
    landing_url TEXT,
    audience_segment TEXT,
    scheduled_at TIMESTAMP WITH TIME ZONE,
    status TEXT DEFAULT 'DRAFT', -- 'DRAFT', 'QUEUED', 'PUBLISHING', 'COMPLETED', 'FAILED'
    created_by TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.campaign_jobs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    campaign_id UUID REFERENCES public.marketing_campaigns_v2(id) ON DELETE CASCADE,
    channel TEXT NOT NULL, -- 'WHATSAPP', 'INSTAGRAM', 'FACEBOOK', 'TIKTOK', 'GMAIL'
    status TEXT DEFAULT 'QUEUED',
    platform_post_id TEXT,
    errors TEXT,
    last_retry_at TIMESTAMP WITH TIME ZONE,
    retry_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.channel_credentials (
    channel TEXT PRIMARY KEY,
    encrypted_token TEXT,
    refresh_token TEXT,
    scopes TEXT[],
    expires_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 18. RLS POLICIES FOR NEW SYSTEMS
ALTER TABLE public.bottle_passports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bottle_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.marketing_campaigns_v2 ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Read Passports" ON public.bottle_passports;
CREATE POLICY "Public Read Passports" ON public.bottle_passports FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Read Bottle Events" ON public.bottle_events;
CREATE POLICY "Public Read Bottle Events" ON public.bottle_events FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admins manage marketing v2" ON public.marketing_campaigns_v2;
CREATE POLICY "Admins manage marketing v2" ON public.marketing_campaigns_v2 FOR ALL TO authenticated USING (true);

-- 19. AFFILIATE ECOSYSTEM
CREATE TABLE IF NOT EXISTS public.affiliates (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    referral_code TEXT UNIQUE NOT NULL,
    promotion_channels TEXT[],
    status TEXT DEFAULT 'Pending', -- 'Pending', 'Approved', 'Suspended'
    total_sales NUMERIC DEFAULT 0,
    total_commission_earned NUMERIC DEFAULT 0,
    current_level TEXT DEFAULT 'Starter', -- 'Starter', 'Growth', 'Pro', 'Elite'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.affiliate_clicks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    affiliate_id UUID REFERENCES public.affiliates(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id),
    ip_address TEXT,
    device_info TEXT,
    referrer_url TEXT,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.commissions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    affiliate_id UUID REFERENCES public.affiliates(id),
    order_id BIGINT REFERENCES public.orders(id),
    amount NUMERIC NOT NULL,
    status TEXT DEFAULT 'PENDING', -- 'PENDING', 'APPROVED', 'PAYABLE', 'PAID', 'REVERSED'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.affiliate_payouts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    affiliate_id UUID REFERENCES public.affiliates(id),
    amount NUMERIC NOT NULL,
    method TEXT DEFAULT 'M-Pesa',
    status TEXT DEFAULT 'REQUESTED',
    transaction_ref TEXT,
    processed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 20. PARTNER INVITES (Magic Links)
CREATE TABLE IF NOT EXISTS public.partner_invites (
    token TEXT PRIMARY KEY,
    role TEXT NOT NULL, -- 'RIDER', 'SUPPLIER', 'AFFILIATE'
    email TEXT,
    phone TEXT,
    target_id TEXT, -- Associated ID in respective status table
    is_used BOOLEAN DEFAULT false,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 21. SECURITY & SESSIONS
CREATE TABLE IF NOT EXISTS public.security_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    device_name TEXT,
    device_type TEXT, -- 'Mobile', 'Desktop'
    browser TEXT,
    ip_address TEXT,
    last_active_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    is_current_session BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON public.security_sessions(user_id);

ALTER TABLE public.security_sessions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users view own sessions" ON public.security_sessions;
CREATE POLICY "Users view own sessions" ON public.security_sessions FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users delete own sessions" ON public.security_sessions;
CREATE POLICY "Users delete own sessions" ON public.security_sessions FOR DELETE USING (auth.uid() = user_id);

-- 22. INTEGRATIONS (v2)
CREATE TABLE IF NOT EXISTS public.integration_nodes (
    id TEXT PRIMARY KEY, -- 'WHATSAPP', 'META', 'TIKTOK', 'GOOGLE'
    status TEXT DEFAULT 'Not Connected', -- 'Connected', 'Not Connected', 'Error'
    config JSONB DEFAULT '{}'::JSONB,
    last_tested_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

ALTER TABLE public.integration_nodes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admins manage integrations" ON public.integration_nodes;
CREATE POLICY "Admins manage integrations" ON public.integration_nodes FOR ALL TO authenticated USING (true);

-- 23. DATA QUALITY ALERTS
CREATE TABLE IF NOT EXISTS public.data_quality_alerts (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    issue_type TEXT NOT NULL,
    severity TEXT,
    description TEXT,
    affected_count INTEGER DEFAULT 0,
    status TEXT DEFAULT 'OPEN',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 24. MISSION DEFINITIONS
CREATE TABLE IF NOT EXISTS public.mission_definitions (
    id TEXT PRIMARY KEY,
    label TEXT NOT NULL,
    description TEXT,
    xp_reward INTEGER DEFAULT 100,
    target_count INTEGER DEFAULT 1,
    category TEXT DEFAULT 'Patron',
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

ALTER TABLE public.mission_definitions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read Missions" ON public.mission_definitions;
CREATE POLICY "Public Read Missions" ON public.mission_definitions FOR SELECT USING (true);

-- 25. SETTINGS INITIALIZATION
INSERT INTO public.settings (key, value) VALUES
('onboarding_config', '{
    "rider_steps": [
        {"id": "welcome", "label": "Welcome Screen", "enabled": true},
        {"id": "phone", "label": "Phone Verification", "enabled": true},
        {"id": "identity", "label": "Identity Profile", "enabled": true},
        {"id": "vehicle", "label": "Logistics Specs", "enabled": true},
        {"id": "verification", "label": "Photo Verification", "enabled": true},
        {"id": "agreement", "label": "Legal Agreement", "enabled": true},
        {"id": "biometrics", "label": "Bio-Lock Enrollment", "enabled": true}
    ],
    "rules": {
        "min_age": 18,
        "require_license": true,
        "auto_approve": false
    }
}'::jsonb)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

-- Seed Initial Missions
INSERT INTO public.mission_definitions (id, label, description, xp_reward, target_count)
VALUES
('buy-mixers', 'Explore Mixers', 'Purchase 2 or more mixers in a single order.', 250, 2),
('review-product', 'Patron Voice', 'Share your tasting notes with the community.', 100, 1),
('refer-friend', 'Spread the Word', 'Bring an elite patron to the bar grid.', 500, 1)
ON CONFLICT (id) DO NOTHING;
